import assert from 'node:assert/strict';
import test from 'node:test';
import { randomUUID } from 'node:crypto';
import { Pool, type PoolClient } from 'pg';
import { seedTwoSchoolFixture } from './test-fixtures.js';

const databaseUrl = process.env.DATABASE_URL;

async function withRollback(pool: Pool, fn: (client: PoolClient) => Promise<void>): Promise<void> {
  const client = await pool.connect();
  await client.query('BEGIN');
  try { await fn(client); } finally { await client.query('ROLLBACK'); client.release(); }
}
async function expectPgConstraint(client: PoolClient, sql: string, params: unknown[], expectedCodes: string[]): Promise<void> {
  const savepoint = `sp_${randomUUID().replaceAll('-', '')}`; await client.query(`SAVEPOINT ${savepoint}`);
  try { await client.query(sql, params); assert.fail('Expected PostgreSQL to reject the statement.'); }
  catch (error) { const code = typeof error === 'object' && error !== null && 'code' in error ? String((error as { code?: unknown }).code) : ''; assert.ok(expectedCodes.includes(code), `Expected PostgreSQL code ${expectedCodes.join('/')} but received ${code || 'unknown'}.`); }
  finally { await client.query(`ROLLBACK TO SAVEPOINT ${savepoint}`); await client.query(`RELEASE SAVEPOINT ${savepoint}`); }
}

test('SW-020 PostgreSQL relational foundation', { skip: !databaseUrl }, async (t) => {
  const pool = new Pool({ connectionString: databaseUrl, max: 4, application_name: 'grantdesk-schoolwide:schema-test' });
  try {
    await t.test('all eighteen ordered migrations are recorded', async () => { const result=await pool.query<{version:string}>('SELECT version FROM grantdesk_schema_migrations ORDER BY version'); assert.deepEqual(result.rows.map((row)=>row.version),['001_identity_and_tenancy.sql','002_organization_academics.sql','003_schedule_calendar_policy.sql','004_idempotency_outbox_audit.sql','005_policy_actor_tenant_integrity.sql','006_staff_sessions.sql','007_student_credentials_action_proofs.sql','008_checkins.sql','009_hall_pass_core.sql','010_audit_corrections.sql','011_teacher_application.sql','012_classroom_integration.sql','013_classroom_oauth_redirect_binding.sql','014_admin_policy_value_validation.sql','015_realtime_operations.sql','016_legacy_readonly_importer.sql','017_shadow_migration_parity.sql','018_credential_continuity_recovery.sql']); });
    await t.test('same display name remains legal while canonical students stay distinct',async()=>{await withRollback(pool,async(client)=>{const ids=await seedTwoSchoolFixture(client);const result=await client.query<{id:string}>('SELECT id FROM students WHERE school_id = $1 AND display_name = $2 ORDER BY id',[ids.schoolA,'Student Same']);assert.deepEqual(result.rows.map((row)=>row.id),[ids.studentA,ids.studentA2]);});});
    await t.test('one canonical student can hold multiple section enrollments',async()=>{await withRollback(pool,async(client)=>{const ids=await seedTwoSchoolFixture(client);await client.query(`INSERT INTO enrollments (school_id, section_id, student_id) VALUES ($1,$2,$3),($1,$4,$3)`,[ids.schoolA,ids.sectionA1,ids.studentA,ids.sectionA2]);const result=await client.query<{section_id:string}>('SELECT section_id FROM enrollments WHERE school_id=$1 AND student_id=$2 ORDER BY section_id',[ids.schoolA,ids.studentA]);assert.deepEqual(result.rows.map((row)=>row.section_id),[ids.sectionA1,ids.sectionA2]);});});
    await t.test('raw SQL cannot cross school boundaries for enrollment',async()=>{await withRollback(pool,async(client)=>{const ids=await seedTwoSchoolFixture(client);await expectPgConstraint(client,'INSERT INTO enrollments (school_id, section_id, student_id) VALUES ($1,$2,$3)',[ids.schoolA,ids.sectionB1,ids.studentA],['23503']);});});
    await t.test('raw SQL cannot attach an organization A user to an organization B school role',async()=>{await withRollback(pool,async(client)=>{const ids=await seedTwoSchoolFixture(client);await expectPgConstraint(client,`INSERT INTO user_roles (organization_id,school_id,user_id,role) VALUES ($1,$2,$3,'TEACHER')`,[ids.orgA,ids.schoolB,ids.teacherA],['23503']);});});
    await t.test('authoritative identity aliases cannot collide within one school namespace',async()=>{await withRollback(pool,async(client)=>{const ids=await seedTwoSchoolFixture(client);await client.query(`INSERT INTO student_identity_aliases (school_id,student_id,kind,value,normalized_value,source) VALUES ($1,$2,'EMAIL','learner@north.example.invalid','learner@north.example.invalid','MANUAL')`,[ids.schoolA,ids.studentA]);await expectPgConstraint(client,`INSERT INTO student_identity_aliases (school_id,student_id,kind,value,normalized_value,source) VALUES ($1,$2,'EMAIL','LEARNER@north.example.invalid','learner@north.example.invalid','MANUAL')`,[ids.schoolA,ids.studentA2],['23505']);});});
    await t.test('inactive enrollment is retained instead of deleted',async()=>{await withRollback(pool,async(client)=>{const ids=await seedTwoSchoolFixture(client);const inserted=await client.query<{id:string}>(`INSERT INTO enrollments (school_id,section_id,student_id) VALUES ($1,$2,$3) RETURNING id`,[ids.schoolA,ids.sectionA1,ids.studentA]);const enrollmentId=inserted.rows[0]?.id;assert.ok(enrollmentId);await client.query(`UPDATE enrollments SET status='INACTIVE',left_at=now(),updated_at=now() WHERE id=$1`,[enrollmentId]);const result=await client.query<{status:string;student_exists:boolean}>(`SELECT e.status,EXISTS(SELECT 1 FROM students s WHERE s.id=e.student_id) AS student_exists FROM enrollments e WHERE e.id=$1`,[enrollmentId]);assert.equal(result.rows[0]?.status,'INACTIVE');assert.equal(result.rows[0]?.student_exists,true);});});
    await t.test('invalid academic, schedule, policy and access intervals fail at the database boundary',async()=>{await withRollback(pool,async(client)=>{const ids=await seedTwoSchoolFixture(client);await expectPgConstraint(client,`INSERT INTO academic_terms (school_id,academic_year_id,name,ordinal,starts_on,ends_on) VALUES ($1,$2,'Broken Term',1,DATE '2027-01-10',DATE '2027-01-01')`,[ids.schoolA,ids.yearA],['23514']);const profile=await client.query<{id:string}>(`INSERT INTO schedule_profiles (school_id,name,key) VALUES ($1,'Normal Day','NORMAL') RETURNING id`,[ids.schoolA]);await expectPgConstraint(client,`INSERT INTO schedule_periods (school_id,schedule_profile_id,period_code,starts_at_local,ends_at_local,ordinal_by_time) VALUES ($1,$2,'P1',TIME '10:00',TIME '09:00',1)`,[ids.schoolA,profile.rows[0]?.id],['23514']);});});
    await t.test('known runtime policy values reject malformed types and impossible bounds at the database boundary',async()=>{await withRollback(pool,async(client)=>{const ids=await seedTwoSchoolFixture(client);const set=await client.query<{id:string}>(`INSERT INTO school_policy_sets (organization_id,school_id,academic_year_id,name,effective_from) VALUES ($1,$2,$3,'Policy validation proof',DATE '2026-09-08') RETURNING id`,[ids.orgA,ids.schoolA,ids.yearA]);await expectPgConstraint(client,`INSERT INTO policy_values (school_id,policy_set_id,policy_key,typed_value_json) VALUES ($1,$2,'DAILY_LIMIT',$3::jsonb)`,[ids.schoolA,set.rows[0]?.id,JSON.stringify('three')],['23514']);});});
    await t.test('migration evidence, shadow parity, and recovery artifacts are tenant-bound',async()=>{await withRollback(pool,async(client)=>{const ids=await seedTwoSchoolFixture(client);const fp='a'.repeat(64);const run=await client.query<{id:string}>(`INSERT INTO migration_import_runs (organization_id,school_id,source_snapshot_fingerprint,source_alias,source_schema_version,source_exported_at,mode,status,finished_at) VALUES ($1,$2,$3,'synthetic-v24','2026-09-05-session-a',now(),'IMPORT_SHADOW','PASS',now()) RETURNING id`,[ids.orgA,ids.schoolA,fp]);const runId=run.rows[0]!.id;const continuity=await client.query<{id:string}>(`INSERT INTO migration_credential_continuity_runs (organization_id,school_id,shadow_import_run_id,source_snapshot_fingerprint,status,artifact_digest,created_by_user_id) VALUES ($1,$2,$3,$4,'PASS',$5,$6) RETURNING id`,[ids.orgA,ids.schoolA,runId,fp,'b'.repeat(64),ids.teacherA]);await client.query(`INSERT INTO migration_recovery_artifacts (organization_id,school_id,continuity_run_id,source_snapshot_fingerprint,artifact_digest,artifact_json) VALUES ($1,$2,$3,$4,$5,'{}'::jsonb)`,[ids.orgA,ids.schoolA,continuity.rows[0]!.id,fp,'b'.repeat(64)]);await expectPgConstraint(client,`INSERT INTO migration_credential_continuity_runs (organization_id,school_id,shadow_import_run_id,source_snapshot_fingerprint,status,artifact_digest,created_by_user_id) VALUES ($1,$2,$3,$4,'PASS',$5,$6)`,[ids.orgA,ids.schoolB,runId,fp,'c'.repeat(64),ids.teacherA],['23503']);});});
    await t.test('credential continuity tables contain no secret-bearing columns',async()=>{const result=await pool.query<{column_name:string}>(`SELECT column_name FROM information_schema.columns WHERE table_schema='public' AND table_name IN ('migration_credential_continuity_runs','migration_credential_continuity_records','migration_recovery_artifacts') AND column_name = ANY($1::text[])`,[['pin','secret_hash','secret_salt','pepper','legacy_pin_salt','action_proof','raw_legacy_key']]);assert.deepEqual(result.rows,[]);});
    await t.test('required hot-path indexes exist',async()=>{const expected=['migration_shadow_records_run_surface_idx','migration_shadow_parity_school_time_idx','migration_credential_continuity_school_time_idx','migration_credential_continuity_records_run_idx','migration_credential_continuity_records_student_idx','migration_recovery_artifacts_digest_idx'];const result=await pool.query<{indexname:string}>(`SELECT indexname FROM pg_indexes WHERE schemaname='public' AND indexname=ANY($1::text[])`,[expected]);const names=new Set(result.rows.map((row)=>row.indexname));for(const name of expected)assert.ok(names.has(name),`Missing required index ${name}.`);});
  } finally { await pool.end(); }
});
