export function teacherAppHtml(): string {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>GrantDesk Teacher</title>
<style>
:root{font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#172033;background:#f6f7fb;color-scheme:light}
*{box-sizing:border-box} body{margin:0;min-height:100vh} button,input,select{font:inherit} button,select,input{min-height:44px} button{cursor:pointer}
button:focus-visible,input:focus-visible,select:focus-visible,summary:focus-visible{outline:3px solid currentColor;outline-offset:3px}
header{position:sticky;top:0;z-index:20;background:#172033;color:white;padding:12px 20px;box-shadow:0 2px 10px #0002}.brand{font-weight:800;letter-spacing:.02em}.shell{max-width:1440px;margin:auto;padding:18px}.operational{display:grid;grid-template-columns:minmax(220px,2fr) repeat(4,minmax(120px,1fr));gap:12px;align-items:stretch}.card{background:white;border:1px solid #dfe3ec;border-radius:14px;padding:14px;box-shadow:0 4px 16px #26334f0c}.metric strong{font-size:1.75rem;display:block}.warning{border-left:6px solid currentColor}.warning::before{content:"Warning: ";font-weight:800}.ok::before{content:"Status: ";font-weight:800}.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-top:16px}.list{list-style:none;margin:0;padding:0}.list li{border-top:1px solid #e6e9f0;padding:12px 0;display:flex;gap:12px;align-items:center;justify-content:space-between}.subtle{color:#596276;font-size:.92rem}.pill{display:inline-block;border:1px solid currentColor;border-radius:999px;padding:3px 8px;font-size:.82rem;font-weight:700}.urgent{font-weight:800;text-decoration:underline}.actions{display:flex;gap:8px;flex-wrap:wrap}details{margin-top:16px}summary{font-weight:800;cursor:pointer;padding:12px 0}.roster-row{display:grid;grid-template-columns:minmax(160px,1fr) auto auto;gap:10px;align-items:center}.status-line{min-height:1.5em;margin:8px 0}dialog{border:0;border-radius:16px;max-width:min(520px,calc(100vw - 32px));width:100%;padding:0;box-shadow:0 20px 80px #0005}dialog::backdrop{background:#10182a99}.dialog-body{padding:20px}.field{display:grid;gap:6px;margin:14px 0}.field input,.field select{width:100%;padding:8px;border:1px solid #aab2c2;border-radius:8px}.dialog-actions{display:flex;justify-content:flex-end;gap:8px}.policy-grid{display:grid;gap:10px}.policy-row{display:grid;grid-template-columns:minmax(180px,1fr) minmax(120px,1fr) auto;gap:8px;align-items:end}
@media(max-width:850px){.operational{grid-template-columns:1fr 1fr}.section-card{grid-column:1/-1}.grid{grid-template-columns:1fr}.roster-row,.policy-row{grid-template-columns:1fr}.actions button{flex:1 1 140px}}
@media(max-width:500px){.shell{padding:10px}.operational{grid-template-columns:1fr}.section-card{grid-column:auto}.card{border-radius:10px}.actions{display:grid;grid-template-columns:1fr}}
</style>
</head>
<body>
<header><div class="brand">GrantDesk · Teacher</div></header>
<main class="shell" id="teacher-app">
<p id="auth-state" class="status-line ok">Checking staff session.</p>
<section class="operational" aria-label="Current classroom operations">
  <div class="card section-card"><label for="section-select"><strong>Current section</strong></label><select id="section-select" aria-describedby="section-help"><option value="">Choose a section</option></select><div id="section-help" class="subtle">Only sections assigned to your authenticated account are listed.</div><div id="schedule-line" class="subtle"></div></div>
  <div class="card metric"><span>Students out</span><strong id="out-count">—</strong></div>
  <div class="card metric"><span>Waiting</span><strong id="queue-count">—</strong></div>
  <div class="card metric"><span>Checked in</span><strong id="checkin-count">—</strong></div>
  <div class="card metric"><span>Missing</span><strong id="missing-count">—</strong></div>
</section>
<div id="warnings" role="status" aria-live="polite" class="status-line"></div>
<div class="grid">
<section class="card" aria-labelledby="out-heading"><h2 id="out-heading">Out now</h2><ul id="out-list" class="list"><li class="subtle">Select a section.</li></ul></section>
<section class="card" aria-labelledby="queue-heading"><h2 id="queue-heading">Waiting queue</h2><ol id="queue-list" class="list"><li class="subtle">Select a section.</li></ol></section>
</div>
<details class="card" id="roster-details"><summary>Roster & Check-In</summary><div id="roster-list" class="list"></div></details>
<details class="card"><summary>Pass evidence</summary><div id="evidence-panel" class="subtle">Choose Evidence beside a student to load this marking period only.</div></details>
<details class="card"><summary>Allowed policy controls</summary><div id="policy-controls" class="policy-grid subtle">Controls appear only when school policy marks a key as teacher-overridable.</div></details>
<p class="subtle">Live updates currently use bounded polling fallback. Realtime transport is a later operations batch; correctness does not depend on it.</p>
<div id="announcer" aria-live="polite" aria-atomic="true" class="status-line"></div>
</main>
<dialog id="return-dialog" aria-labelledby="return-title"><form method="dialog" class="dialog-body" id="return-form"><h2 id="return-title">End active pass</h2><input type="hidden" id="return-pass-id"><div class="field"><label for="return-reason">Private staff reason</label><input id="return-reason" maxlength="1000" required autocomplete="off"><span class="subtle">Recorded in staff/audit evidence.</span></div><div class="dialog-actions"><button value="cancel" type="button" data-dialog-cancel>Cancel</button><button value="confirm" type="submit">End pass</button></div></form></dialog>
<dialog id="correction-dialog" aria-labelledby="correction-title"><form method="dialog" class="dialog-body" id="correction-form"><h2 id="correction-title">Void pass countability</h2><input type="hidden" id="correction-pass-id"><div class="field"><label for="correction-reason">Private correction reason</label><input id="correction-reason" maxlength="1000" required autocomplete="off"></div><div class="dialog-actions"><button value="cancel" type="button" data-dialog-cancel>Cancel</button><button value="confirm" type="submit">Void countability</button></div></form></dialog>
<script>
(()=>{
'use strict';
const tokenKey='grantdesk.schoolwide.staffToken';
const state={token:sessionStorage.getItem(tokenKey)||'',sectionId:'',timer:null,inFlight:false,policySection:'',lastFocus:null};
const byId=id=>document.getElementById(id);
const announce=message=>{byId('announcer').textContent=message};
const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const seconds=value=>{const m=Math.floor(value/60),s=value%60;return m?m+'m '+s+'s':s+'s'};
const key=()=>crypto.randomUUID();
function safeReplace(element,html){if(element.contains(document.activeElement))return false;element.innerHTML=html;return true}
async function api(path,options={}){if(!state.token)throw new Error('Staff sign-in is required.');const headers={...(options.headers||{}),authorization:'Bearer '+state.token};const response=await fetch(path,{...options,headers,cache:'no-store'});let body={};try{body=await response.json()}catch{}if(response.status===401){state.token='';sessionStorage.removeItem(tokenKey);throw new Error('Your staff session expired. Sign in again.')}if(!response.ok)throw new Error(body.message||('Request failed ('+response.status+').'));return body}
async function loadSections(){if(!state.token){byId('auth-state').textContent='Staff sign-in is required before private classroom data can load.';return}try{const data=await api('/api/v1/teacher/sections');const select=byId('section-select');safeReplace(select,'<option value="">Choose a section</option>'+data.sections.map(s=>'<option value="'+escapeHtml(s.sectionId)+'">'+escapeHtml((s.periodLabel?('Period '+s.periodLabel+' · '):'')+s.name)+'</option>').join(''));byId('auth-state').textContent=data.sections.length?'Staff session verified. Choose an assigned section.':'Staff session verified, but no assigned teacher sections are authorized.';if(data.sections.length===1){select.value=data.sections[0].sectionId;select.dispatchEvent(new Event('change'))}}catch(error){byId('auth-state').textContent=error.message}}
function renderWarnings(items){const el=byId('warnings');safeReplace(el,items.length?items.map(item=>'<div class="card warning">'+escapeHtml(item.message)+'</div>').join(''):'<span class="ok">No current operational warnings.</span>')}
function renderOut(items){byId('out-count').textContent=items.length;safeReplace(byId('out-list'),items.length?items.map(item=>'<li><div><strong>'+escapeHtml(item.studentName)+'</strong><div class="subtle">'+escapeHtml(item.destinationName)+' · '+seconds(item.elapsedSeconds)+(item.warning?'<br><span class="urgent">Warning: expected time exceeded</span>':'')+'</div></div><div class="actions"><button type="button" data-return-pass="'+escapeHtml(item.passId)+'">End pass</button></div></li>').join(''):'<li class="subtle">No students are out.</li>')}
function renderQueue(items){byId('queue-count').textContent=items.length;safeReplace(byId('queue-list'),items.length?items.map((item,index)=>'<li><div><strong>#'+(index+1)+' · '+escapeHtml(item.studentName)+'</strong><div class="subtle">'+escapeHtml(item.destinationName)+' · waiting '+seconds(item.waitingSeconds)+(item.warning?'<br><span class="urgent">Warning: request expires soon</span>':'')+'</div></div></li>').join(''):'<li class="subtle">Queue is empty.</li>')}
function renderRoster(items){safeReplace(byId('roster-list'),items.map(item=>'<div class="roster-row"><div><strong>'+escapeHtml(item.displayName)+'</strong><div class="subtle">Check-In: '+(item.checkedIn?'recorded':'not recorded')+'</div></div><button type="button" data-evidence-student="'+escapeHtml(item.studentId)+'">Evidence</button><button type="button" data-checkin-student="'+escapeHtml(item.studentId)+'" '+(item.checkedIn?'disabled':'')+'>Backup Check-In</button></div>').join('')||'<p class="subtle">No active students are enrolled.</p>')}
function renderPolicies(controls){if(state.policySection===state.sectionId)return;state.policySection=state.sectionId;safeReplace(byId('policy-controls'),controls.length?controls.map((item,index)=>{const value=typeof item.value==='string'?item.value:JSON.stringify(item.value);return '<form class="policy-row" data-policy-key="'+escapeHtml(item.policyKey)+'"><label>'+escapeHtml(item.policyKey)+'<span class="subtle">Current source: '+escapeHtml(item.source)+'</span></label><input name="value" value="'+escapeHtml(value)+'" aria-label="New value for '+escapeHtml(item.policyKey)+'"><button type="submit">Apply</button><input name="reason" required maxlength="1000" placeholder="Private reason" aria-label="Reason for '+escapeHtml(item.policyKey)+' override"></form>'}).join(''):'<p class="subtle">No policy keys are currently marked teacher-overridable.</p>')}
function renderSchedule(snapshot){const session=snapshot.schedule?.session;byId('schedule-line').textContent=snapshot.academicDate+(session?.status==='IN_SESSION'&&session.period?(' · '+session.period.startsAtLocal+'–'+session.period.endsAtLocal):' · schedule not in active session')}
async function loadLive({announceChange=false}={}){if(!state.sectionId||state.inFlight)return;state.inFlight=true;try{const data=await api('/api/v1/teacher/sections/'+encodeURIComponent(state.sectionId)+'/live');renderSchedule(data);renderWarnings(data.warnings);renderOut(data.activePasses);renderQueue(data.queue);renderRoster(data.roster);renderPolicies(data.policyControls);byId('checkin-count').textContent=data.checkInSummary.checkedIn;byId('missing-count').textContent=data.checkInSummary.missing;if(announceChange)announce('Classroom state refreshed.');schedulePoll(data.transport.pollAfterMs)}catch(error){renderWarnings([{message:error.message}]);schedulePoll(10000)}finally{state.inFlight=false}}
function schedulePoll(ms){clearTimeout(state.timer);if(state.sectionId)state.timer=setTimeout(()=>loadLive(),Math.max(2000,Math.min(60000,ms||5000)))}
async function loadEvidence(studentId){try{const data=await api('/api/v1/teacher/sections/'+encodeURIComponent(state.sectionId)+'/students/'+encodeURIComponent(studentId)+'/pass-evidence?limit=25');const panel=byId('evidence-panel');safeReplace(panel,'<h3>'+escapeHtml(data.studentName)+' · current marking period</h3><p class="subtle">'+escapeHtml(data.termStartsOn)+' to '+escapeHtml(data.termEndsOn)+' · at most '+data.limit+' records</p>'+(data.items.length?'<ul class="list">'+data.items.map(item=>'<li><div><strong>'+escapeHtml(item.destinationName)+'</strong><div class="subtle">'+escapeHtml(item.startedAt)+' · effective '+escapeHtml(item.effectiveCountability)+'</div></div>'+(item.status!=='OUT'&&item.effectiveCountability==='COUNTABLE'?'<button type="button" data-correct-pass="'+escapeHtml(item.passId)+'">Void countability</button>':'')+'</li>').join('')+'</ul>':'<p>No pass evidence in this marking period.</p>'));panel.scrollIntoView({block:'nearest'});announce('Pass evidence loaded for '+data.studentName+'.')}catch(error){announce(error.message)}}
function openDialog(dialog,idField,value,focusField){byId(idField).value=value;const el=byId(dialog);state.lastFocus=document.activeElement;el.showModal();queueMicrotask(()=>byId(focusField).focus())}
function closeDialog(dialog){byId(dialog).close();if(state.lastFocus&&document.contains(state.lastFocus))state.lastFocus.focus()}
byId('section-select').addEventListener('change',event=>{state.sectionId=event.target.value;state.policySection='';clearTimeout(state.timer);byId('evidence-panel').textContent='Choose Evidence beside a student to load this marking period only.';if(state.sectionId)loadLive({announceChange:true})});
document.addEventListener('click',event=>{const button=event.target.closest('button');if(!button)return;if(button.dataset.returnPass)openDialog('return-dialog','return-pass-id',button.dataset.returnPass,'return-reason');if(button.dataset.evidenceStudent)loadEvidence(button.dataset.evidenceStudent);if(button.dataset.correctPass)openDialog('correction-dialog','correction-pass-id',button.dataset.correctPass,'correction-reason');if(button.dataset.checkinStudent)backupCheckIn(button.dataset.checkinStudent);if(button.hasAttribute('data-dialog-cancel'))closeDialog(button.closest('dialog').id)});
byId('return-form').addEventListener('submit',async event=>{event.preventDefault();const passId=byId('return-pass-id').value,reason=byId('return-reason').value.trim();if(!reason)return;try{await api('/api/v1/teacher/passes/'+encodeURIComponent(passId)+'/return',{method:'POST',headers:{'content-type':'application/json','idempotency-key':key()},body:JSON.stringify({reason})});byId('return-reason').value='';closeDialog('return-dialog');announce('Pass ended and queue settlement completed.');await loadLive()}catch(error){announce(error.message)}});
byId('correction-form').addEventListener('submit',async event=>{event.preventDefault();const passId=byId('correction-pass-id').value,reason=byId('correction-reason').value.trim();if(!reason)return;try{await api('/api/v1/teacher/passes/'+encodeURIComponent(passId)+'/corrections',{method:'POST',headers:{'content-type':'application/json','idempotency-key':key()},body:JSON.stringify({type:'VOID_COUNTABILITY',reason})});byId('correction-reason').value='';closeDialog('correction-dialog');announce('Pass countability was voided without changing the original pass record.')}catch(error){announce(error.message)}});
async function backupCheckIn(studentId){try{await api('/api/v1/teacher/sections/'+encodeURIComponent(state.sectionId)+'/checkins',{method:'POST',headers:{'content-type':'application/json','idempotency-key':key()},body:JSON.stringify({studentId,note:'Teacher dashboard backup Check-In'})});announce('Backup Check-In recorded.');await loadLive()}catch(error){announce(error.message)}}
byId('policy-controls').addEventListener('submit',async event=>{const form=event.target.closest('form[data-policy-key]');if(!form)return;event.preventDefault();const formData=new FormData(form);const raw=String(formData.get('value')||'').trim(),reason=String(formData.get('reason')||'').trim();if(!reason)return;let value;try{value=JSON.parse(raw)}catch{value=raw}try{await api('/api/v1/teacher/sections/'+encodeURIComponent(state.sectionId)+'/policy-overrides/'+encodeURIComponent(form.dataset.policyKey),{method:'POST',headers:{'content-type':'application/json','idempotency-key':key()},body:JSON.stringify({value,reason})});announce('Policy override saved with audit evidence.');state.policySection='';await loadLive()}catch(error){announce(error.message)}});
window.grantDeskTeacherSession=token=>{if(typeof token!=='string'||!token.trim())return false;state.token=token.trim();sessionStorage.setItem(tokenKey,state.token);loadSections();return true};
loadSections();
})();
</script>
</body>
</html>`;
}
