import Fastify, { type FastifyInstance } from 'fastify';
import { registerAdminConsoleRoutes } from './admin-console/routes.js';
import { AdminConsoleService } from './admin-console/service.js';
import { registerAdminStructureRoutes } from './admin-console/structure-routes.js';
import { AdminStructureService } from './admin-console/structure.js';
import type { AdminConsoleServiceOptions } from './admin-console/types.js';
import { registerAuditCorrectionRoutes } from './audit-corrections/routes.js';
import { AuditCorrectionService } from './audit-corrections/service.js';
import type { AuditCorrectionServiceOptions } from './audit-corrections/types.js';
import { StaffAuthorizationService } from './auth/authorization.js';
import { DisabledStaffIdentityProvider } from './auth/provider.js';
import { registerStaffAuthRoutes } from './auth/routes.js';
import { StaffAuthenticationService } from './auth/service.js';
import type { StaffIdentityProvider } from './auth/types.js';
import { DisabledClassroomProvider } from './classroom/provider.js';
import { registerClassroomRoutes } from './classroom/routes.js';
import { ClassroomIntegrationService, type ClassroomIntegrationServiceOptions } from './classroom/service.js';
import type { ClassroomProvider } from './classroom/types.js';
import { registerCheckInRoutes } from './checkins/routes.js';
import { CheckInService } from './checkins/service.js';
import type { CheckInServiceOptions } from './checkins/types.js';
import type { AppConfig } from './config.js';
import { registerCredentialContinuityRoutes } from './credential-continuity/routes.js';
import { CredentialContinuityService } from './credential-continuity/service.js';
import type { Database } from './db/database.js';
import { registerHallPassRoutes } from './hall-pass/routes.js';
import { HallPassService } from './hall-pass/service.js';
import type { HallPassServiceOptions } from './hall-pass/types.js';
import { registerLegacyImportRoutes } from './legacy-import/routes.js';
import { LegacyReadOnlyImporterService } from './legacy-import/service.js';
import { InProcessRealtimeBroker } from './realtime/broker.js';
import { registerRealtimeBrowserAcceleration } from './realtime/browser-acceleration.js';
import { ClassroomScheduledSyncWorker } from './realtime/classroom-scheduler.js';
import { OperationsHealthService } from './realtime/operations-service.js';
import { OutboxDeliveryWorker } from './realtime/outbox-worker.js';
import { registerRealtimeRoutes } from './realtime/routes.js';
import { OperationsRuntime } from './realtime/runtime.js';
import type { RealtimeBroker } from './realtime/types.js';
import { registerSchedulePolicyRoutes } from './schedule-policy/routes.js';
import { SchedulePolicyService } from './schedule-policy/service.js';
import { registerSecurityConsoleRoutes } from './security-console/routes.js';
import { SecurityConsoleService } from './security-console/service.js';
import type { SecurityConsoleServiceOptions } from './security-console/types.js';
import { DisabledStudentIdentityProvider } from './student-credentials/provider.js';
import { registerStudentCredentialRoutes } from './student-credentials/routes.js';
import { StudentCredentialService, type StudentCredentialServiceOptions } from './student-credentials/service.js';
import type { StudentIdentityProvider } from './student-credentials/types.js';
import { registerTeacherApplicationRoutes } from './teacher-app/routes.js';
import { TeacherApplicationService } from './teacher-app/service.js';
import type { TeacherApplicationServiceOptions } from './teacher-app/types.js';

export type BuildAppOptions = {
  config: AppConfig; database: Database; identityProvider?: StaffIdentityProvider; sessionTtlMs?: number;
  studentIdentityProvider?: StudentIdentityProvider; studentCredentialOptions?: StudentCredentialServiceOptions;
  checkInOptions?: CheckInServiceOptions; hallPassOptions?: HallPassServiceOptions; auditCorrectionOptions?: AuditCorrectionServiceOptions;
  teacherApplicationOptions?: TeacherApplicationServiceOptions; classroomProvider?: ClassroomProvider; classroomOptions?: ClassroomIntegrationServiceOptions;
  securityConsoleOptions?: SecurityConsoleServiceOptions; adminConsoleOptions?: AdminConsoleServiceOptions; realtimeBroker?: RealtimeBroker;
};

export function buildApp({config,database,identityProvider=new DisabledStaffIdentityProvider(),sessionTtlMs,studentIdentityProvider=new DisabledStudentIdentityProvider(),studentCredentialOptions,checkInOptions,hallPassOptions,auditCorrectionOptions,teacherApplicationOptions,classroomProvider=new DisabledClassroomProvider(),classroomOptions,securityConsoleOptions,adminConsoleOptions,realtimeBroker=new InProcessRealtimeBroker()}:BuildAppOptions):FastifyInstance {
  const app=Fastify({logger:config.nodeEnv==='test'?false:{level:config.logLevel},bodyLimit:1_048_576,trustProxy:false});
  const authenticationOptions=sessionTtlMs===undefined?{}:{sessionTtlMs};
  const authentication=new StaffAuthenticationService(database,identityProvider,authenticationOptions);
  const authorization=new StaffAuthorizationService(database);
  const schedulePolicy=new SchedulePolicyService(database);
  const studentCredentials=new StudentCredentialService(database,studentIdentityProvider,studentCredentialOptions??{});
  const checkins=new CheckInService(database,checkInOptions??{});
  const hallPass=new HallPassService(database,hallPassOptions??{});
  const corrections=new AuditCorrectionService(database,auditCorrectionOptions??{});
  const teacherApp=new TeacherApplicationService(database,schedulePolicy,teacherApplicationOptions??{});
  const classroom=new ClassroomIntegrationService(database,classroomProvider,classroomOptions??{});
  const securityConsole=new SecurityConsoleService(database,securityConsoleOptions??{});
  const adminConsole=new AdminConsoleService(database,adminConsoleOptions??{});
  const adminNow=adminConsoleOptions?.now??(()=>new Date());
  const adminStructure=new AdminStructureService(database,adminNow);
  const legacyImporter=new LegacyReadOnlyImporterService(database);
  const credentialContinuity=new CredentialContinuityService(database);
  const operationsHealth=new OperationsHealthService(database);
  const outboxWorker=new OutboxDeliveryWorker(database,realtimeBroker,{instanceId:config.instanceId,batchSize:config.outboxWorkerBatchSize??50});
  const classroomWorker=new ClassroomScheduledSyncWorker(database,classroom,{instanceId:config.instanceId,batchSize:config.classroomSyncBatchSize??20});
  const operationsRuntime=new OperationsRuntime(outboxWorker,classroomWorker,{outboxIntervalMs:config.outboxWorkerIntervalMs??1_000,classroomIntervalMs:config.classroomSyncIntervalMs??300_000});
  const deploymentTier=config.deploymentTier??'local';
  const releaseSha=config.releaseSha??'local';

  registerRealtimeBrowserAcceleration(app);
  registerStaffAuthRoutes(app,{authentication,authorization});
  registerSchedulePolicyRoutes(app,{authentication,authorization,schedulePolicy});
  registerStudentCredentialRoutes(app,studentCredentials);
  registerCheckInRoutes(app,{authentication,authorization,checkins});
  registerHallPassRoutes(app,{hallPass,studentIdentityProvider});
  registerAuditCorrectionRoutes(app,{authentication,authorization,corrections});
  registerTeacherApplicationRoutes(app,{authentication,authorization,teacherApp,hallPass});
  registerClassroomRoutes(app,{authentication,authorization,classroom});
  registerSecurityConsoleRoutes(app,{authentication,authorization,securityConsole});
  registerAdminConsoleRoutes(app,{authentication,authorization,adminConsole});
  registerAdminStructureRoutes(app,{authentication,authorization,adminConsole,structure:adminStructure,database});
  registerRealtimeRoutes(app,{authentication,authorization,studentIdentityProvider,database,broker:realtimeBroker,health:operationsHealth});
  registerLegacyImportRoutes(app,{authentication,authorization,importer:legacyImporter});
  registerCredentialContinuityRoutes(app,{authentication,authorization,continuity:credentialContinuity});

  app.get('/',async()=>({service:'grantdesk-schoolwide',version:'sw-170',status:'staging-release-readiness',deploymentTier,releaseSha}));
  app.get('/health/live',async()=>({status:'ok',service:'grantdesk-schoolwide',instanceId:config.instanceId,deploymentTier,releaseSha}));
  app.get('/health/ready',async(_request,reply)=>{try{await database.query('SELECT 1 AS ready');return{status:'ready',service:'grantdesk-schoolwide',deploymentTier,releaseSha};}catch{reply.code(503);return{status:'not-ready',service:'grantdesk-schoolwide',deploymentTier,releaseSha};}});
  if(config.operationsWorkersEnabled===true)operationsRuntime.start();
  app.addHook('onClose',async()=>{operationsRuntime.stop();await database.close();});
  return app;
}
