import { randomUUID } from 'node:crypto';
import type { FastifyInstance, FastifyReply, FastifyRequest } from 'fastify';
import { z } from 'zod';
import { StaffAuthorizationService } from '../auth/authorization.js';
import { StaffAuthenticationService } from '../auth/service.js';
import { AuthenticationError, AuthorizationError, staffRoleValues } from '../auth/types.js';
import { AdminConsoleService } from './service.js';
import { AdminConsoleError } from './types.js';
import { adminConsoleHtml } from './ui.js';

const idSchema = z.string().regex(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);
const dateSchema = z.string().regex(/^\d{4}-\d{2}-\d{2}$/);
const limitSchema = z.coerce.number().int().min(1).max(250).default(100);
const reasonSchema = z.string().trim().min(1).max(1000);
const roleBody = z.object({ role: z.enum(staffRoleValues), reason: reasonSchema, validUntil: z.string().datetime().nullable().optional() }).strict();
const policyBody = z.object({ typedValue: z.unknown(), teacherOverrideAllowed: z.boolean(), reason: reasonSchema }).strict();
const calendarBody = z.object({ academicDate: dateSchema, isSchoolDay: z.boolean(), scheduleProfileId: idSchema.nullable(), label: z.string().trim().max(200).nullable(), reason: reasonSchema }).strict();
const destinationBody = z.object({
  name: z.string().trim().min(1).max(120),
  category: z.enum(['RESTROOM','OFFICE','NURSE','COUNSELOR','OTHER']),
  securityVisible: z.boolean(),
  studentSelectable: z.boolean(),
  defaultExpectedMinutes: z.number().int().min(1).max(240).nullable(),
  capacity: z.number().int().min(1).max(1000).nullable(),
  reason: reasonSchema,
}).strict();
const accessBody = z.object({
  studentId: idSchema,
  sectionId: idSchema.nullable(),
  accessMode: z.enum(['STANDARD','UNLIMITED','ESCORT_ONLY']),
  reasonPrivate: z.string().trim().min(1).max(1000),
  validFrom: z.string().datetime(),
  validUntil: z.string().datetime().nullable(),
  reason: reasonSchema,
}).strict();
const reviewBody = z.object({ resolution: z.enum(['RESOLVED_MATCH','RESOLVED_NEW','DISMISSED']), reason: reasonSchema }).strict();

function bearerToken(request: FastifyRequest): string {
  const header=request.headers.authorization;
  if(!header?.startsWith('Bearer ')) throw new AuthenticationError();
  const token=header.slice(7).trim();
  if(!token) throw new AuthenticationError();
  return token;
}
function idempotencyKey(request:FastifyRequest):string|null {
  const value=request.headers['idempotency-key'];
  if(typeof value!=='string') return null;
  const trimmed=value.trim();
  return trimmed.length>0&&trimmed.length<=200?trimmed:null;
}
function correlationIdFor(request:FastifyRequest,reply:FastifyReply):string {
  const supplied=request.headers['x-correlation-id'];
  const correlationId=typeof supplied==='string'&&idSchema.safeParse(supplied).success?supplied:randomUUID();
  reply.header('x-correlation-id',correlationId);
  return correlationId;
}
function sendError(reply:FastifyReply,error:unknown,requestId:string):boolean {
  if(error instanceof AdminConsoleError){reply.code(error.statusCode).send({code:error.code,message:error.message,requestId,retryable:error.retryable});return true;}
  if(error instanceof AuthenticationError||error instanceof AuthorizationError){reply.code(error.statusCode).send({code:error instanceof AuthenticationError?'AUTH_REQUIRED':'ADMIN_SCOPE_DENIED',message:error.message,requestId,retryable:false});return true;}
  if(error instanceof Error && 'code' in error && (error as {code?:string}).code==='23505'){reply.code(409).send({code:'ADMIN_CONFLICT',message:'That administrator change conflicts with an existing school record.',requestId,retryable:false});return true;}
  return false;
}
async function principalFor(request:FastifyRequest,authentication:StaffAuthenticationService){return authentication.authenticate(bearerToken(request));}

export type RegisterAdminConsoleRoutesOptions={authentication:StaffAuthenticationService;authorization:StaffAuthorizationService;adminConsole:AdminConsoleService};

export function registerAdminConsoleRoutes(app:FastifyInstance,{authentication,authorization,adminConsole}:RegisterAdminConsoleRoutesOptions):void {
  app.get('/admin',async(_request,reply)=>{reply.header('content-type','text/html; charset=utf-8');reply.header('cache-control','no-store');reply.header('content-security-policy',"default-src 'self'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; base-uri 'none'; frame-ancestors 'none'; form-action 'self'");return adminConsoleHtml();});

  app.get('/api/v1/admin/overview',async(request,reply)=>{const requestId=correlationIdFor(request,reply);try{const principal=await principalFor(request,authentication);const schoolId=adminConsole.resolveSchoolId(principal,'admin.school.read_all_operational');authorization.requireSchoolCapability(principal,schoolId,'admin.school.read_all_operational');return {...await adminConsole.overview(principal),requestId};}catch(error){if(sendError(reply,error,requestId))return;throw error;}});
  app.get('/api/v1/admin/staff',async(request,reply)=>{const requestId=correlationIdFor(request,reply);const parsed=z.object({limit:limitSchema}).strict().safeParse(request.query);if(!parsed.success)return reply.code(400).send({code:'ADMIN_REQUEST_INVALID',message:'Staff query is invalid.',requestId,retryable:false});try{const principal=await principalFor(request,authentication);const schoolId=adminConsole.resolveSchoolId(principal,'admin.school.read_all_operational');authorization.requireSchoolCapability(principal,schoolId,'admin.school.read_all_operational');return {...await adminConsole.listStaff(principal,parsed.data.limit),requestId};}catch(error){if(sendError(reply,error,requestId))return;throw error;}});
  app.get('/api/v1/admin/sections',async(request,reply)=>{const requestId=correlationIdFor(request,reply);const parsed=z.object({limit:limitSchema}).strict().safeParse(request.query);if(!parsed.success)return reply.code(400).send({code:'ADMIN_REQUEST_INVALID',message:'Section query is invalid.',requestId,retryable:false});try{const principal=await principalFor(request,authentication);const schoolId=adminConsole.resolveSchoolId(principal,'admin.school.read_all_operational');authorization.requireSchoolCapability(principal,schoolId,'admin.school.read_all_operational');return {...await adminConsole.listSections(principal,parsed.data.limit),requestId};}catch(error){if(sendError(reply,error,requestId))return;throw error;}});
  app.get('/api/v1/admin/policies',async(request,reply)=>{const requestId=correlationIdFor(request,reply);const parsed=z.object({limit:limitSchema}).strict().safeParse(request.query);if(!parsed.success)return reply.code(400).send({code:'ADMIN_REQUEST_INVALID',message:'Policy query is invalid.',requestId,retryable:false});try{const principal=await principalFor(request,authentication);const schoolId=adminConsole.resolveSchoolId(principal,'admin.policies.manage');authorization.requireSchoolCapability(principal,schoolId,'admin.policies.manage');return {...await adminConsole.listPolicies(principal,parsed.data.limit),requestId};}catch(error){if(sendError(reply,error,requestId))return;throw error;}});
  app.get('/api/v1/admin/destinations',async(request,reply)=>{const requestId=correlationIdFor(request,reply);try{const principal=await principalFor(request,authentication);const schoolId=adminConsole.resolveSchoolId(principal,'admin.destinations.manage');authorization.requireSchoolCapability(principal,schoolId,'admin.destinations.manage');return {...await adminConsole.listDestinations(principal),requestId};}catch(error){if(sendError(reply,error,requestId))return;throw error;}});
  app.get('/api/v1/admin/calendar',async(request,reply)=>{const requestId=correlationIdFor(request,reply);const parsed=z.object({from:dateSchema,to:dateSchema}).strict().safeParse(request.query);if(!parsed.success)return reply.code(400).send({code:'ADMIN_REQUEST_INVALID',message:'Calendar range is invalid.',requestId,retryable:false});const from=new Date(parsed.data.from+'T00:00:00Z'),to=new Date(parsed.data.to+'T00:00:00Z');if(to<from||to.getTime()-from.getTime()>90*86400000)return reply.code(400).send({code:'ADMIN_REQUEST_INVALID',message:'Calendar range must be no longer than 90 days.',requestId,retryable:false});try{const principal=await principalFor(request,authentication);const schoolId=adminConsole.resolveSchoolId(principal,'admin.calendar.manage');authorization.requireSchoolCapability(principal,schoolId,'admin.calendar.manage');return {...await adminConsole.listCalendar(principal,parsed.data.from,parsed.data.to),requestId};}catch(error){if(sendError(reply,error,requestId))return;throw error;}});
  app.get('/api/v1/admin/student-access',async(request,reply)=>{const requestId=correlationIdFor(request,reply);const parsed=z.object({limit:limitSchema}).strict().safeParse(request.query);if(!parsed.success)return reply.code(400).send({code:'ADMIN_REQUEST_INVALID',message:'Student access query is invalid.',requestId,retryable:false});try{const principal=await principalFor(request,authentication);const schoolId=adminConsole.resolveSchoolId(principal,'admin.student_access.manage');authorization.requireSchoolCapability(principal,schoolId,'admin.student_access.manage');return {...await adminConsole.listStudentAccess(principal,parsed.data.limit),requestId};}catch(error){if(sendError(reply,error,requestId))return;throw error;}});
  app.get('/api/v1/admin/integrations/reviews',async(request,reply)=>{const requestId=correlationIdFor(request,reply);const parsed=z.object({limit:limitSchema}).strict().safeParse(request.query);if(!parsed.success)return reply.code(400).send({code:'ADMIN_REQUEST_INVALID',message:'Integration review query is invalid.',requestId,retryable:false});try{const principal=await principalFor(request,authentication);const schoolId=adminConsole.resolveSchoolId(principal,'admin.integrations.review');authorization.requireSchoolCapability(principal,schoolId,'admin.integrations.review');return {...await adminConsole.listIntegrationReviews(principal,parsed.data.limit),requestId};}catch(error){if(sendError(reply,error,requestId))return;throw error;}});
  app.get('/api/v1/admin/audit',async(request,reply)=>{const requestId=correlationIdFor(request,reply);const parsed=z.object({limit:z.coerce.number().int().min(1).max(100).default(50),before:z.string().datetime().optional(),from:z.string().datetime().optional()}).strict().safeParse(request.query);if(!parsed.success)return reply.code(400).send({code:'ADMIN_REQUEST_INVALID',message:'Audit query is invalid.',requestId,retryable:false});try{const principal=await principalFor(request,authentication);const schoolId=adminConsole.resolveSchoolId(principal,'admin.audit.read_bounded');authorization.requireSchoolCapability(principal,schoolId,'admin.audit.read_bounded');return {...await adminConsole.listAudit(principal,{limit:parsed.data.limit,...(parsed.data.before?{before:new Date(parsed.data.before)}:{}),...(parsed.data.from?{from:new Date(parsed.data.from)}:{})}),requestId};}catch(error){if(sendError(reply,error,requestId))return;throw error;}});

  app.post('/api/v1/admin/staff/:userId/roles',async(request,reply)=>{const requestId=correlationIdFor(request,reply),key=idempotencyKey(request),params=z.object({userId:idSchema}).strict().safeParse(request.params),body=roleBody.safeParse(request.body);if(!key||!params.success||!body.success)return reply.code(400).send({code:'ADMIN_REQUEST_INVALID',message:'Target user, role, private reason, and Idempotency-Key are required.',requestId,retryable:false});try{const principal=await principalFor(request,authentication);const schoolId=adminConsole.resolveSchoolId(principal,'admin.staff.roles.manage');authorization.requireSchoolCapability(principal,schoolId,'admin.staff.roles.manage');const result=await adminConsole.grantRole({principal,targetUserId:params.data.userId,role:body.data.role,reason:body.data.reason,idempotencyKey:key,correlationId:requestId,...(body.data.validUntil?{validUntil:new Date(body.data.validUntil)}:{})});reply.code(201);return {...result,requestId};}catch(error){if(sendError(reply,error,requestId))return;throw error;}});
  app.post('/api/v1/admin/roles/:roleId/revoke',async(request,reply)=>{const requestId=correlationIdFor(request,reply),key=idempotencyKey(request),params=z.object({roleId:idSchema}).strict().safeParse(request.params),body=z.object({reason:reasonSchema}).strict().safeParse(request.body);if(!key||!params.success||!body.success)return reply.code(400).send({code:'ADMIN_REQUEST_INVALID',message:'Role grant, private reason, and Idempotency-Key are required.',requestId,retryable:false});try{const principal=await principalFor(request,authentication);const schoolId=adminConsole.resolveSchoolId(principal,'admin.staff.roles.manage');authorization.requireSchoolCapability(principal,schoolId,'admin.staff.roles.manage');const result=await adminConsole.revokeRole({principal,roleId:params.data.roleId,reason:body.data.reason,idempotencyKey:key,correlationId:requestId});reply.code(201);return {...result,requestId};}catch(error){if(sendError(reply,error,requestId))return;throw error;}});
  app.put('/api/v1/admin/policies/:policyValueId',async(request,reply)=>{const requestId=correlationIdFor(request,reply),key=idempotencyKey(request),params=z.object({policyValueId:idSchema}).strict().safeParse(request.params),body=policyBody.safeParse(request.body);if(!key||!params.success||!body.success)return reply.code(400).send({code:'ADMIN_REQUEST_INVALID',message:'Policy value, explicit value/override setting, private reason, and Idempotency-Key are required.',requestId,retryable:false});try{const principal=await principalFor(request,authentication);const schoolId=adminConsole.resolveSchoolId(principal,'admin.policies.manage');authorization.requireSchoolCapability(principal,schoolId,'admin.policies.manage');const result=await adminConsole.updatePolicyValue({principal,policyValueId:params.data.policyValueId,typedValue:body.data.typedValue,teacherOverrideAllowed:body.data.teacherOverrideAllowed,reason:body.data.reason,idempotencyKey:key,correlationId:requestId});reply.code(201);return {...result,requestId};}catch(error){if(sendError(reply,error,requestId))return;throw error;}});
  app.put('/api/v1/admin/calendar/day',async(request,reply)=>{const requestId=correlationIdFor(request,reply),key=idempotencyKey(request),body=calendarBody.safeParse(request.body);if(!key||!body.success)return reply.code(400).send({code:'ADMIN_REQUEST_INVALID',message:'Calendar day, private reason, and Idempotency-Key are required.',requestId,retryable:false});try{const principal=await principalFor(request,authentication);const schoolId=adminConsole.resolveSchoolId(principal,'admin.calendar.manage');authorization.requireSchoolCapability(principal,schoolId,'admin.calendar.manage');const result=await adminConsole.upsertCalendarDay({principal,...body.data,idempotencyKey:key,correlationId:requestId});reply.code(201);return {...result,requestId};}catch(error){if(sendError(reply,error,requestId))return;throw error;}});
  app.post('/api/v1/admin/destinations',async(request,reply)=>{const requestId=correlationIdFor(request,reply),key=idempotencyKey(request),body=destinationBody.safeParse(request.body);if(!key||!body.success)return reply.code(400).send({code:'ADMIN_REQUEST_INVALID',message:'Destination configuration, private reason, and Idempotency-Key are required.',requestId,retryable:false});try{const principal=await principalFor(request,authentication);const schoolId=adminConsole.resolveSchoolId(principal,'admin.destinations.manage');authorization.requireSchoolCapability(principal,schoolId,'admin.destinations.manage');const result=await adminConsole.createDestination({principal,...body.data,idempotencyKey:key,correlationId:requestId});reply.code(201);return {...result,requestId};}catch(error){if(sendError(reply,error,requestId))return;throw error;}});
  app.post('/api/v1/admin/student-access',async(request,reply)=>{const requestId=correlationIdFor(request,reply),key=idempotencyKey(request),body=accessBody.safeParse(request.body);if(!key||!body.success)return reply.code(400).send({code:'ADMIN_REQUEST_INVALID',message:'Student access configuration, reasons, and Idempotency-Key are required.',requestId,retryable:false});try{const principal=await principalFor(request,authentication);const schoolId=adminConsole.resolveSchoolId(principal,'admin.student_access.manage');authorization.requireSchoolCapability(principal,schoolId,'admin.student_access.manage');const result=await adminConsole.createStudentAccessRule({principal,studentId:body.data.studentId,sectionId:body.data.sectionId,accessMode:body.data.accessMode,reasonPrivate:body.data.reasonPrivate,validFrom:new Date(body.data.validFrom),validUntil:body.data.validUntil?new Date(body.data.validUntil):null,reason:body.data.reason,idempotencyKey:key,correlationId:requestId});reply.code(201);return {...result,requestId};}catch(error){if(sendError(reply,error,requestId))return;throw error;}});
  app.post('/api/v1/admin/integrations/reviews/:reviewId/resolve',async(request,reply)=>{const requestId=correlationIdFor(request,reply),key=idempotencyKey(request),params=z.object({reviewId:idSchema}).strict().safeParse(request.params),body=reviewBody.safeParse(request.body);if(!key||!params.success||!body.success)return reply.code(400).send({code:'ADMIN_REQUEST_INVALID',message:'Review item, resolution, private reason, and Idempotency-Key are required.',requestId,retryable:false});try{const principal=await principalFor(request,authentication);const schoolId=adminConsole.resolveSchoolId(principal,'admin.integrations.review');authorization.requireSchoolCapability(principal,schoolId,'admin.integrations.review');const result=await adminConsole.resolveIntegrationReview({principal,reviewId:params.data.reviewId,resolution:body.data.resolution,reason:body.data.reason,idempotencyKey:key,correlationId:requestId});reply.code(201);return {...result,requestId};}catch(error){if(sendError(reply,error,requestId))return;throw error;}});
}
