import { randomUUID } from 'node:crypto';
import type { FastifyInstance, FastifyReply, FastifyRequest } from 'fastify';
import { z } from 'zod';
import { StaffAuthorizationService } from '../auth/authorization.js';
import { StaffAuthenticationService } from '../auth/service.js';
import { AuthenticationError, AuthorizationError } from '../auth/types.js';
import { AdminConsoleService } from './service.js';
import { AdminStructureService } from './structure.js';
import { AdminConsoleError } from './types.js';

const id=z.string().regex(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i),reason=z.string().trim().min(1).max(1000);
function bearer(r:FastifyRequest):string{const h=r.headers.authorization;if(!h?.startsWith('Bearer '))throw new AuthenticationError();const t=h.slice(7).trim();if(!t)throw new AuthenticationError();return t;}
function idem(r:FastifyRequest):string|null{const v=r.headers['idempotency-key'];if(typeof v!=='string')return null;const s=v.trim();return s&&s.length<=200?s:null;}
function requestId(r:FastifyRequest,reply:FastifyReply):string{const supplied=r.headers['x-correlation-id'];const value=typeof supplied==='string'&&id.safeParse(supplied).success?supplied:randomUUID();reply.header('x-correlation-id',value);return value;}
function send(reply:FastifyReply,error:unknown,rid:string):boolean{if(error instanceof AdminConsoleError){reply.code(error.statusCode).send({code:error.code,message:error.message,requestId:rid,retryable:error.retryable});return true;}if(error instanceof AuthenticationError||error instanceof AuthorizationError){reply.code(error.statusCode).send({code:error instanceof AuthenticationError?'AUTH_REQUIRED':'ADMIN_SCOPE_DENIED',message:error.message,requestId:rid,retryable:false});return true;}if(error instanceof Error&&'code' in error&&((error as {code?:string}).code==='23505'||(error as {code?:string}).code==='23514')){reply.code(409).send({code:'ADMIN_CONFIG_CONFLICT',message:'That configuration conflicts with an existing or validated school record.',requestId:rid,retryable:false});return true;}return false;}

export function registerAdminStructureRoutes(app:FastifyInstance,input:{authentication:StaffAuthenticationService;authorization:StaffAuthorizationService;adminConsole:AdminConsoleService;structure:AdminStructureService}):void{
  const {authentication,authorization,adminConsole,structure}=input;
  async function principal(r:FastifyRequest){return authentication.authenticate(bearer(r));}

  app.get('/api/v1/admin/schedules',async(r,reply)=>{const rid=requestId(r,reply);try{const p=await principal(r),schoolId=adminConsole.resolveSchoolId(p,'admin.calendar.manage');authorization.requireSchoolCapability(p,schoolId,'admin.calendar.manage');return{schoolId,rows:await structure.listScheduleProfiles(schoolId),requestId:rid};}catch(e){if(send(reply,e,rid))return;throw e;}});

  app.post('/api/v1/admin/schedules',async(r,reply)=>{const rid=requestId(r,reply),key=idem(r),body=z.object({name:z.string().trim().min(1).max(120),key:z.string().trim().min(1).max(40),reason}).strict().safeParse(r.body);if(!key||!body.success)return reply.code(400).send({code:'ADMIN_REQUEST_INVALID',message:'Schedule profile and private reason are required.',requestId:rid,retryable:false});try{const p=await principal(r),schoolId=adminConsole.resolveSchoolId(p,'admin.calendar.manage');authorization.requireSchoolCapability(p,schoolId,'admin.calendar.manage');const result=await structure.createScheduleProfile({principal:p,schoolId,name:body.data.name,key:body.data.key,reason:body.data.reason,idempotencyKey:key,correlationId:rid});reply.code(201);return{...result,requestId:rid};}catch(e){if(send(reply,e,rid))return;throw e;}});

  app.post('/api/v1/admin/schedules/:profileId/periods',async(r,reply)=>{const rid=requestId(r,reply),key=idem(r),params=z.object({profileId:id}).strict().safeParse(r.params),body=z.object({periodCode:z.string().trim().min(1).max(30),startsAtLocal:z.string().regex(/^\d{2}:\d{2}:\d{2}$/),endsAtLocal:z.string().regex(/^\d{2}:\d{2}:\d{2}$/),ordinalByTime:z.number().int().min(1).max(100),reason}).strict().safeParse(r.body);if(!key||!params.success||!body.success)return reply.code(400).send({code:'ADMIN_REQUEST_INVALID',message:'Schedule period and private reason are required.',requestId:rid,retryable:false});try{const p=await principal(r),schoolId=adminConsole.resolveSchoolId(p,'admin.calendar.manage');authorization.requireSchoolCapability(p,schoolId,'admin.calendar.manage');const result=await structure.createSchedulePeriod({principal:p,schoolId,profileId:params.data.profileId,...body.data,idempotencyKey:key,correlationId:rid});reply.code(201);return{...result,requestId:rid};}catch(e){if(send(reply,e,rid))return;throw e;}});

  app.post('/api/v1/admin/sections/:sectionId/status',async(r,reply)=>{const rid=requestId(r,reply),key=idem(r),params=z.object({sectionId:id}).strict().safeParse(r.params),body=z.object({status:z.enum(['ACTIVE','INACTIVE']),reason}).strict().safeParse(r.body);if(!key||!params.success||!body.success)return reply.code(400).send({code:'ADMIN_REQUEST_INVALID',message:'Section status and private reason are required.',requestId:rid,retryable:false});try{const p=await principal(r),schoolId=adminConsole.resolveSchoolId(p,'admin.sections.manage');authorization.requireSchoolCapability(p,schoolId,'admin.sections.manage');const result=await structure.setSectionStatus({principal:p,schoolId,sectionId:params.data.sectionId,...body.data,idempotencyKey:key,correlationId:rid});reply.code(201);return{...result,requestId:rid};}catch(e){if(send(reply,e,rid))return;throw e;}});

  app.post('/api/v1/admin/enrollments/:enrollmentId/status',async(r,reply)=>{const rid=requestId(r,reply),key=idem(r),params=z.object({enrollmentId:id}).strict().safeParse(r.params),body=z.object({status:z.enum(['ACTIVE','INACTIVE','PENDING_REVIEW']),reason}).strict().safeParse(r.body);if(!key||!params.success||!body.success)return reply.code(400).send({code:'ADMIN_REQUEST_INVALID',message:'Enrollment status and private reason are required.',requestId:rid,retryable:false});try{const p=await principal(r),schoolId=adminConsole.resolveSchoolId(p,'admin.sections.manage');authorization.requireSchoolCapability(p,schoolId,'admin.sections.manage');const result=await structure.setEnrollmentStatus({principal:p,schoolId,enrollmentId:params.data.enrollmentId,...body.data,idempotencyKey:key,correlationId:rid});reply.code(201);return{...result,requestId:rid};}catch(e){if(send(reply,e,rid))return;throw e;}});

  app.put('/api/v1/admin/destinations/:destinationId',async(r,reply)=>{const rid=requestId(r,reply),key=idem(r),params=z.object({destinationId:id}).strict().safeParse(r.params),body=z.object({active:z.boolean(),securityVisible:z.boolean(),studentSelectable:z.boolean(),defaultExpectedMinutes:z.number().int().min(1).max(240).nullable(),capacity:z.number().int().min(1).max(1000).nullable(),reason}).strict().safeParse(r.body);if(!key||!params.success||!body.success)return reply.code(400).send({code:'ADMIN_REQUEST_INVALID',message:'Destination configuration and private reason are required.',requestId:rid,retryable:false});try{const p=await principal(r),schoolId=adminConsole.resolveSchoolId(p,'admin.destinations.manage');authorization.requireSchoolCapability(p,schoolId,'admin.destinations.manage');const result=await structure.updateDestination({principal:p,schoolId,destinationId:params.data.destinationId,...body.data,idempotencyKey:key,correlationId:rid});reply.code(201);return{...result,requestId:rid};}catch(e){if(send(reply,e,rid))return;throw e;}});
}
