import { createHash } from 'node:crypto';
import type { QueryResultRow } from 'pg';
import type { Database, QueryExecutor } from '../db/database.js';
import { supportsTransactions } from '../db/database.js';
import { AdminConsoleError, type AdminMutationResult, type AdminPrincipal } from './types.js';

interface IdempotencyRow extends QueryResultRow {
  id:string; operation:string; request_fingerprint:string; status:'IN_PROGRESS'|'COMPLETED'|'FAILED'; response_json_sanitized:unknown; expires_at:Date;
}
function hash(value:string):string{return createHash('sha256').update(value,'utf8').digest('hex');}
function isResult(value:unknown):value is AdminMutationResult{if(!value||typeof value!=='object')return false;const r=value as Record<string,unknown>;return typeof r.action==='string'&&typeof r.targetType==='string'&&typeof r.targetId==='string'&&typeof r.recordedAt==='string';}

export type AdminScheduleProfileRow={profileId:string;name:string;key:string;status:'ACTIVE'|'INACTIVE';periods:readonly{periodId:string;periodCode:string;startsAtLocal:string;endsAtLocal:string;ordinalByTime:number}[]};

export class AdminStructureService {
  readonly #db:Database; readonly #now:()=>Date; readonly #ttl=24*60*60_000;
  constructor(database:Database,now:()=>Date=()=>new Date()){this.#db=database;this.#now=now;}

  async listScheduleProfiles(schoolId:string):Promise<readonly AdminScheduleProfileRow[]>{
    const rows=await this.#db.query<{profile_id:string;profile_name:string;profile_key:string;profile_status:'ACTIVE'|'INACTIVE';period_id:string|null;period_code:string|null;starts_at_local:string|null;ends_at_local:string|null;ordinal_by_time:number|null}&QueryResultRow>(
      `SELECT sp.id AS profile_id,sp.name AS profile_name,sp.key AS profile_key,sp.status AS profile_status,
              p.id AS period_id,p.period_code,p.starts_at_local::text,p.ends_at_local::text,p.ordinal_by_time
         FROM schedule_profiles sp LEFT JOIN schedule_periods p ON p.school_id=sp.school_id AND p.schedule_profile_id=sp.id
        WHERE sp.school_id=$1 ORDER BY sp.status,sp.name,sp.id,p.ordinal_by_time,p.id LIMIT 500`,[schoolId]);
    const map=new Map<string,AdminScheduleProfileRow>();for(const r of rows){const cur=map.get(r.profile_id)??{profileId:r.profile_id,name:r.profile_name,key:r.profile_key,status:r.profile_status,periods:[]};const periods=[...cur.periods];if(r.period_id&&r.period_code&&r.starts_at_local&&r.ends_at_local&&r.ordinal_by_time!==null)periods.push({periodId:r.period_id,periodCode:r.period_code,startsAtLocal:r.starts_at_local,endsAtLocal:r.ends_at_local,ordinalByTime:r.ordinal_by_time});map.set(r.profile_id,{...cur,periods});}return[...map.values()].slice(0,100);
  }

  async setSectionStatus(input:{principal:AdminPrincipal;schoolId:string;sectionId:string;status:'ACTIVE'|'INACTIVE';reason:string;idempotencyKey:string;correlationId:string}):Promise<AdminMutationResult>{const at=this.#now();return this.#mutate({...input,operation:'ADMIN_SECTION_STATUS',targetType:'SECTION',targetId:input.sectionId,parts:[input.status],at,work:async tx=>{const rows=await tx.query<{id:string;school_id:string}&QueryResultRow>(`SELECT id,school_id FROM sections WHERE id=$1 FOR UPDATE`,[input.sectionId]);if(!rows[0])throw new AdminConsoleError('ADMIN_SECTION_NOT_FOUND','Section was not found.',404);if(rows[0].school_id!==input.schoolId)throw new AdminConsoleError('ADMIN_SCHOOL_SCOPE_DENIED','Section is outside the authorized school.',403);await tx.query(`UPDATE sections SET status=$2,updated_at=$3::timestamptz WHERE id=$1`,[input.sectionId,input.status,at.toISOString()]);return input.sectionId;}});}

  async setEnrollmentStatus(input:{principal:AdminPrincipal;schoolId:string;enrollmentId:string;status:'ACTIVE'|'INACTIVE'|'PENDING_REVIEW';reason:string;idempotencyKey:string;correlationId:string}):Promise<AdminMutationResult>{const at=this.#now();return this.#mutate({...input,operation:'ADMIN_ENROLLMENT_STATUS',targetType:'ENROLLMENT',targetId:input.enrollmentId,parts:[input.status],at,work:async tx=>{const rows=await tx.query<{id:string;school_id:string;status:string}&QueryResultRow>(`SELECT id,school_id,status FROM enrollments WHERE id=$1 FOR UPDATE`,[input.enrollmentId]);if(!rows[0])throw new AdminConsoleError('ADMIN_ENROLLMENT_NOT_FOUND','Enrollment was not found.',404);if(rows[0].school_id!==input.schoolId)throw new AdminConsoleError('ADMIN_SCHOOL_SCOPE_DENIED','Enrollment is outside the authorized school.',403);const leftAt=input.status==='INACTIVE'?at.toISOString():null;await tx.query(`UPDATE enrollments SET status=$2,left_at=$3::timestamptz,updated_at=$4::timestamptz WHERE id=$1`,[input.enrollmentId,input.status,leftAt,at.toISOString()]);return input.enrollmentId;}});}

  async createScheduleProfile(input:{principal:AdminPrincipal;schoolId:string;name:string;key:string;reason:string;idempotencyKey:string;correlationId:string}):Promise<AdminMutationResult>{const name=input.name.trim(),key=input.key.trim().toUpperCase();if(!name||!key||!/^[A-Z0-9_]+$/.test(key))throw new AdminConsoleError('ADMIN_SCHEDULE_INVALID','Schedule profile name/key is invalid.',400);const at=this.#now();return this.#mutate({...input,operation:'ADMIN_SCHEDULE_PROFILE_CREATE',targetType:'SCHEDULE_PROFILE',targetId:key,parts:[name,key],at,work:async tx=>{const rows=await tx.query<{id:string}&QueryResultRow>(`INSERT INTO schedule_profiles (school_id,name,key,status) VALUES ($1,$2,$3,'ACTIVE') RETURNING id`,[input.schoolId,name,key]);return rows[0]!.id;}});}

  async createSchedulePeriod(input:{principal:AdminPrincipal;schoolId:string;profileId:string;periodCode:string;startsAtLocal:string;endsAtLocal:string;ordinalByTime:number;reason:string;idempotencyKey:string;correlationId:string}):Promise<AdminMutationResult>{const code=input.periodCode.trim();if(!code||!/^\d{2}:\d{2}:\d{2}$/.test(input.startsAtLocal)||!/^\d{2}:\d{2}:\d{2}$/.test(input.endsAtLocal)||input.endsAtLocal<=input.startsAtLocal||!Number.isInteger(input.ordinalByTime)||input.ordinalByTime<1)throw new AdminConsoleError('ADMIN_SCHEDULE_INVALID','Schedule period timing/ordinal is invalid.',400);const at=this.#now();return this.#mutate({...input,operation:'ADMIN_SCHEDULE_PERIOD_CREATE',targetType:'SCHEDULE_PERIOD',targetId:input.profileId,parts:[input.profileId,code,input.startsAtLocal,input.endsAtLocal,String(input.ordinalByTime)],at,work:async tx=>{const profile=await tx.query<{id:string;school_id:string;status:string}&QueryResultRow>(`SELECT id,school_id,status FROM schedule_profiles WHERE id=$1 FOR UPDATE`,[input.profileId]);if(!profile[0])throw new AdminConsoleError('ADMIN_SCHEDULE_NOT_FOUND','Schedule profile was not found.',404);if(profile[0].school_id!==input.schoolId)throw new AdminConsoleError('ADMIN_SCHOOL_SCOPE_DENIED','Schedule profile is outside the authorized school.',403);if(profile[0].status!=='ACTIVE')throw new AdminConsoleError('ADMIN_SCHEDULE_INVALID','Cannot add a period to an inactive schedule profile.',409);const rows=await tx.query<{id:string}&QueryResultRow>(`INSERT INTO schedule_periods (school_id,schedule_profile_id,period_code,starts_at_local,ends_at_local,ordinal_by_time) VALUES ($1,$2,$3,$4::time,$5::time,$6) RETURNING id`,[input.schoolId,input.profileId,code,input.startsAtLocal,input.endsAtLocal,input.ordinalByTime]);return rows[0]!.id;}});}

  async updateDestination(input:{principal:AdminPrincipal;schoolId:string;destinationId:string;active:boolean;securityVisible:boolean;studentSelectable:boolean;defaultExpectedMinutes:number|null;capacity:number|null;reason:string;idempotencyKey:string;correlationId:string}):Promise<AdminMutationResult>{if(input.defaultExpectedMinutes!==null&&(!Number.isInteger(input.defaultExpectedMinutes)||input.defaultExpectedMinutes<1))throw new AdminConsoleError('ADMIN_DESTINATION_INVALID','Expected minutes must be a positive integer.',400);if(input.capacity!==null&&(!Number.isInteger(input.capacity)||input.capacity<1))throw new AdminConsoleError('ADMIN_DESTINATION_INVALID','Capacity must be a positive integer.',400);const at=this.#now();return this.#mutate({...input,operation:'ADMIN_DESTINATION_UPDATE',targetType:'DESTINATION',targetId:input.destinationId,parts:[String(input.active),String(input.securityVisible),String(input.studentSelectable),String(input.defaultExpectedMinutes??''),String(input.capacity??'')],at,work:async tx=>{const rows=await tx.query<{id:string;school_id:string}&QueryResultRow>(`SELECT id,school_id FROM destinations WHERE id=$1 FOR UPDATE`,[input.destinationId]);if(!rows[0])throw new AdminConsoleError('ADMIN_DESTINATION_NOT_FOUND','Destination was not found.',404);if(rows[0].school_id!==input.schoolId)throw new AdminConsoleError('ADMIN_SCHOOL_SCOPE_DENIED','Destination is outside the authorized school.',403);await tx.query(`UPDATE destinations SET active=$2,security_visible=$3,student_selectable=$4,default_expected_minutes=$5,capacity=$6,updated_at=$7::timestamptz WHERE id=$1`,[input.destinationId,input.active,input.securityVisible,input.studentSelectable,input.defaultExpectedMinutes,input.capacity,at.toISOString()]);return input.destinationId;}});}

  async #mutate(input:{principal:AdminPrincipal;schoolId:string;operation:string;targetType:string;targetId:string;reason:string;idempotencyKey:string;correlationId:string;parts:readonly string[];at:Date;work:(tx:QueryExecutor)=>Promise<string>}):Promise<AdminMutationResult>{if(!supportsTransactions(this.#db))throw new Error('Admin structure mutations require transactional database support.');const reason=input.reason.trim();if(!reason||reason.length>1000)throw new AdminConsoleError('ADMIN_REASON_REQUIRED','A concise private administrative reason is required.',400);const fp=hash([input.operation,input.principal.userId,...input.parts,reason].join('\u0000'));return this.#db.transaction(async tx=>{const state=await this.#start(tx,input,fp);if(state.kind==='COMPLETED')return state.response;const targetId=await input.work(tx);const response:AdminMutationResult={action:input.operation,targetType:input.targetType,targetId,recordedAt:input.at.toISOString()};await tx.query(`INSERT INTO audit_events (organization_id,school_id,actor_user_id,actor_kind,action,target_type,target_id,reason,request_id,correlation_id,source,metadata) VALUES ($1,$2,$3,'USER',$4,$5,$6,$7,$8,$8,'APPLICATION',$9::jsonb)`,[input.principal.organizationId,input.schoolId,input.principal.userId,input.operation,input.targetType,targetId,reason,input.correlationId,JSON.stringify({operation:input.operation})]);await tx.query(`INSERT INTO transactional_outbox (organization_id,school_id,topic,event_type,aggregate_type,aggregate_id,correlation_id,payload_json_sanitized) VALUES ($1,$2,'schoolwide.admin',$3,$4,$5::uuid,$6,$7::jsonb)`,[input.principal.organizationId,input.schoolId,input.operation,input.targetType,/^[0-9a-f-]{36}$/i.test(targetId)?targetId:null,input.correlationId,JSON.stringify({action:input.operation,targetType:input.targetType,targetId,actorUserId:input.principal.userId,occurredAt:input.at.toISOString()})]);await tx.query(`UPDATE idempotency_keys SET status='COMPLETED',response_status=201,response_json_sanitized=$2::jsonb,completed_at=$3::timestamptz WHERE id=$1`,[state.id,JSON.stringify(response),input.at.toISOString()]);return response;});}

  async #start(tx:QueryExecutor,input:{principal:AdminPrincipal;schoolId:string;operation:string;idempotencyKey:string;correlationId:string;at:Date},fp:string):Promise<{kind:'NEW';id:string}|{kind:'COMPLETED';response:AdminMutationResult}>{const expires=new Date(input.at.getTime()+this.#ttl);const inserted=await tx.query<{id:string}&QueryResultRow>(`INSERT INTO idempotency_keys (organization_id,school_id,key,operation,request_fingerprint,status,created_at,expires_at,correlation_id) VALUES ($1,$2,$3,$4,$5,'IN_PROGRESS',$6::timestamptz,$7::timestamptz,$8) ON CONFLICT (school_id,key) DO NOTHING RETURNING id`,[input.principal.organizationId,input.schoolId,input.idempotencyKey,input.operation,fp,input.at.toISOString(),expires.toISOString(),input.correlationId]);if(inserted[0])return{kind:'NEW',id:inserted[0].id};const rows=await tx.query<IdempotencyRow>(`SELECT id,operation,request_fingerprint,status,response_json_sanitized,expires_at FROM idempotency_keys WHERE school_id=$1 AND key=$2 FOR UPDATE`,[input.schoolId,input.idempotencyKey]);const row=rows[0];if(!row)throw new AdminConsoleError('IDEMPOTENCY_CONFLICT','Idempotency state is unavailable.',409,true);if(row.operation!==input.operation||row.request_fingerprint!==fp)throw new AdminConsoleError('IDEMPOTENCY_CONFLICT','Idempotency key was already used for a different administrator request.',409);if(row.status==='COMPLETED'&&isResult(row.response_json_sanitized))return{kind:'COMPLETED',response:row.response_json_sanitized};throw new AdminConsoleError('IDEMPOTENCY_CONFLICT','The same administrator request is still being resolved.',409,true);}
}
