export function adminConsoleHtml(): string {
  return String.raw`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>GrantDesk Admin</title>
<style>
:root{font-family:Inter,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color-scheme:light;background:#f4f6f8;color:#17202a}*{box-sizing:border-box}body{margin:0;background:#f4f6f8}button,input,select,textarea{font:inherit}button,input,select{min-height:44px}button:focus-visible,input:focus-visible,select:focus-visible,textarea:focus-visible{outline:3px solid currentColor;outline-offset:2px}.top{position:sticky;top:0;z-index:5;background:#17202a;color:#fff;padding:14px 20px;display:flex;justify-content:space-between;gap:16px}.wrap{max-width:1500px;margin:auto;padding:20px}.notice,.card,.panel,.controls{background:#fff;border:1px solid #d6dde3;border-radius:12px}.notice{padding:12px 14px;margin-bottom:16px}.metrics{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:12px;margin-bottom:16px}.card{padding:16px}.card strong{display:block;font-size:1.7rem}.panel{padding:16px;margin-bottom:16px}h1,h2,h3{margin-top:0}.tabs{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:12px}.btn{border:1px solid #59636d;background:#fff;border-radius:8px;padding:8px 12px;cursor:pointer}.btn.primary{background:#17202a;color:#fff}.btn[aria-selected="true"]{font-weight:800;text-decoration:underline}.table-wrap{overflow:auto}.grid{width:100%;border-collapse:collapse;min-width:760px}.grid th,.grid td{text-align:left;padding:10px;border-bottom:1px solid #e1e6ea;vertical-align:top}.grid th{font-size:.82rem;text-transform:uppercase}.muted{color:#5e6872}.empty{padding:24px;text-align:center;color:#5e6872}.status{min-height:1.4em;margin:8px 0}.health{display:flex;gap:12px;flex-wrap:wrap}.health span{padding:6px 9px;border:1px solid #d6dde3;border-radius:999px}.controls{padding:14px;margin:12px 0}.control-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.field{display:grid;gap:5px}.field label{font-weight:700}.field input,.field select,.field textarea{border:1px solid #9da9b3;border-radius:8px;padding:9px 10px;background:#fff}.field textarea{min-height:92px;resize:vertical}.span2{grid-column:span 2}.actions{display:flex;gap:8px;justify-content:flex-end;align-items:end;flex-wrap:wrap}.row-actions{display:flex;gap:6px;flex-wrap:wrap}dialog{border:0;border-radius:12px;max-width:560px;width:calc(100% - 32px);box-shadow:0 20px 60px rgba(0,0,0,.25)}dialog::backdrop{background:rgba(0,0,0,.45)}dialog form{display:grid;gap:12px}@media(max-width:1000px){.metrics{grid-template-columns:repeat(2,1fr)}.control-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:560px){.wrap{padding:12px}.metrics,.control-grid{grid-template-columns:1fr}.span2{grid-column:auto}.top{flex-direction:column}.grid{min-width:650px}}
</style></head><body>
<header class="top"><strong>GrantDesk · Admin</strong><span id="connection">Staff session required</span></header>
<main class="wrap">
<div class="notice">School-scoped administration only. Sensitive credentials, connection secrets, unrestricted history, and unapproved emergency actions stay outside this surface. Protected changes require a private administrative reason and are audited.</div>
<section class="metrics" aria-label="School administration summary"><div class="card">Active staff<strong id="staffCount">—</strong></div><div class="card">Active sections<strong id="sectionCount">—</strong></div><div class="card">Active students<strong id="studentCount">—</strong></div><div class="card">Open reviews<strong id="reviewCount">—</strong></div><div class="card">Destinations<strong id="destinationCount">—</strong></div></section>
<section class="panel"><h1>School administration</h1><div class="health" id="health" aria-label="Classroom integration health"></div><div id="status" class="status" role="status" aria-live="polite"></div>
<div class="tabs" role="tablist" aria-label="Administration views"><button class="btn" role="tab" aria-selected="true" data-view="staff">Staff & roles</button><button class="btn" role="tab" aria-selected="false" data-view="sections">Sections</button><button class="btn" role="tab" aria-selected="false" data-view="enrollments">Enrollments</button><button class="btn" role="tab" aria-selected="false" data-view="schedules">Schedules</button><button class="btn" role="tab" aria-selected="false" data-view="calendar">Calendar</button><button class="btn" role="tab" aria-selected="false" data-view="policies">Policies</button><button class="btn" role="tab" aria-selected="false" data-view="destinations">Destinations</button><button class="btn" role="tab" aria-selected="false" data-view="access">Student access</button><button class="btn" role="tab" aria-selected="false" data-view="reviews">Sync review</button><button class="btn" role="tab" aria-selected="false" data-view="audit">Corrections & audit</button></div>
<div id="controls"></div><div class="table-wrap" id="content"><div class="empty">Connect an administrator staff session to load school configuration.</div></div></section>
</main>
<dialog id="reasonDialog" aria-labelledby="dialogTitle"><form method="dialog" id="reasonForm"><h2 id="dialogTitle">Confirm administrator action</h2><p id="dialogDescription"></p><div class="field"><label for="reason">Private administrative reason</label><textarea id="reason" maxlength="1000" required></textarea></div><div class="actions"><button class="btn" value="cancel">Cancel</button><button class="btn primary" id="confirm" value="default">Confirm</button></div><div id="dialogStatus" role="status" aria-live="polite"></div></form></dialog>
<script>(function(){'use strict';
var key='grantdesk.schoolwide.staffToken',token=sessionStorage.getItem(key)||'',view='staff',returnFocus=null,pending=null;
var e={connection:document.getElementById('connection'),status:document.getElementById('status'),content:document.getElementById('content'),controls:document.getElementById('controls'),staff:document.getElementById('staffCount'),sections:document.getElementById('sectionCount'),students:document.getElementById('studentCount'),reviews:document.getElementById('reviewCount'),destinations:document.getElementById('destinationCount'),health:document.getElementById('health'),dialog:document.getElementById('reasonDialog'),description:document.getElementById('dialogDescription'),reason:document.getElementById('reason'),dialogStatus:document.getElementById('dialogStatus'),confirm:document.getElementById('confirm')};
function headers(extra){var h={authorization:'Bearer '+token};if(extra)Object.keys(extra).forEach(function(k){h[k]=extra[k]});return h}function text(tag,value,cls){var n=document.createElement(tag);n.textContent=value;if(cls)n.className=cls;return n}function button(label,fn){var b=text('button',label,'btn');b.type='button';b.addEventListener('click',fn);return b}function rid(){return crypto.randomUUID()}function dateOnly(d){return d.toISOString().slice(0,10)}
async function api(url,options){options=options||{};options.headers=headers(options.headers||{});var r=await fetch(url,options),b={};try{b=await r.json()}catch(_e){}if(r.status===401){token='';sessionStorage.removeItem(key);setConnection()}if(!r.ok)throw new Error(b.message||('Request failed ('+r.status+')'));return b}function setConnection(){e.connection.textContent=token?'Administrator session connected':'Staff session required'}
function renderOverview(o){e.staff.textContent=o.summary.activeStaff;e.sections.textContent=o.summary.activeSections;e.students.textContent=o.summary.activeStudents;e.reviews.textContent=o.summary.openIntegrationReviews;e.destinations.textContent=o.summary.activeDestinations;e.health.replaceChildren();[['Classroom active',o.integrationHealth.active],['Revoked',o.integrationHealth.revoked],['Error',o.integrationHealth.error],['Stale links',o.integrationHealth.staleLinks]].forEach(function(x){e.health.appendChild(text('span',x[0]+': '+x[1]))})}
function table(headers,rows){e.content.replaceChildren();if(!rows.length){e.content.appendChild(text('div','No records in this bounded view.','empty'));return}var t=document.createElement('table');t.className='grid';var th=document.createElement('thead'),tr=document.createElement('tr');headers.forEach(function(h){tr.appendChild(text('th',h))});th.appendChild(tr);t.appendChild(th);var tb=document.createElement('tbody');rows.forEach(function(cells){var r=document.createElement('tr');cells.forEach(function(c){var td=document.createElement('td');if(c instanceof Node)td.appendChild(c);else td.textContent=String(c);r.appendChild(td)});tb.appendChild(r)});t.appendChild(tb);e.content.appendChild(t)}
function controls(title,fields,onSubmit){e.controls.replaceChildren();var box=document.createElement('form');box.className='controls';box.addEventListener('submit',function(ev){ev.preventDefault();onSubmit(box)});box.appendChild(text('h3',title));var grid=document.createElement('div');grid.className='control-grid';fields.forEach(function(f){var wrap=document.createElement('div');wrap.className='field'+(f.span2?' span2':'');var lab=text('label',f.label);lab.htmlFor=f.name;var input;if(f.type==='select'){input=document.createElement('select');f.options.forEach(function(o){var op=document.createElement('option');op.value=o.value;op.textContent=o.label;input.appendChild(op)})}else{input=document.createElement(f.type==='textarea'?'textarea':'input');if(f.type!=='textarea')input.type=f.type||'text'}input.id=f.name;input.name=f.name;if(f.required)input.required=true;if(f.value!==undefined)input.value=f.value;if(f.placeholder)input.placeholder=f.placeholder;wrap.append(lab,input);grid.appendChild(wrap)});var a=document.createElement('div');a.className='actions';var submit=text('button','Continue','btn primary');submit.type='submit';a.appendChild(submit);grid.appendChild(a);box.appendChild(grid);e.controls.appendChild(box)}
function mutate(url,method,payload,description,buttonNode){window.grantDeskAdminConfirm(buttonNode||document.activeElement,description,async function(reason){try{payload.reason=reason;await api(url,{method:method,headers:{'idempotency-key':rid(),'content-type':'application/json'},body:JSON.stringify(payload)});e.dialog.close();e.status.textContent='Administrator change recorded and audited.';await refresh()}catch(err){e.dialogStatus.textContent=err.message}})}
function sectionActions(r){var d=document.createElement('div');d.className='row-actions';d.appendChild(button(r.status==='ACTIVE'?'Set inactive':'Set active',function(ev){mutate('/api/v1/admin/sections/'+r.sectionId+'/status','POST',{status:r.status==='ACTIVE'?'INACTIVE':'ACTIVE'},'Change section status for '+r.name+'?',ev.currentTarget)}));return d}
function enrollmentActions(r){var d=document.createElement('div');d.className='row-actions';if(r.status!=='ACTIVE')d.appendChild(button('Set active',function(ev){mutate('/api/v1/admin/enrollments/'+r.enrollmentId+'/status','POST',{status:'ACTIVE'},'Reactivate '+r.studentName+' in '+r.sectionName+'?',ev.currentTarget)}));if(r.status!=='PENDING_REVIEW')d.appendChild(button('Review',function(ev){mutate('/api/v1/admin/enrollments/'+r.enrollmentId+'/status','POST',{status:'PENDING_REVIEW'},'Move this enrollment to staff review?',ev.currentTarget)}));if(r.status!=='INACTIVE')d.appendChild(button('Set inactive',function(ev){mutate('/api/v1/admin/enrollments/'+r.enrollmentId+'/status','POST',{status:'INACTIVE'},'Set this enrollment inactive while retaining history?',ev.currentTarget)}));return d}
function destinationActions(r){var d=document.createElement('div');d.className='row-actions';d.appendChild(button(r.active?'Deactivate':'Activate',function(ev){mutate('/api/v1/admin/destinations/'+r.destinationId,'PUT',{active:!r.active,securityVisible:r.securityVisible,studentSelectable:r.studentSelectable,defaultExpectedMinutes:r.defaultExpectedMinutes,capacity:r.capacity},'Change destination availability for '+r.name+'?',ev.currentTarget)}));return d}
function reviewActions(r){var d=document.createElement('div');d.className='row-actions';if(r.status==='OPEN')d.appendChild(button('Dismiss review',function(ev){mutate('/api/v1/admin/integrations/reviews/'+r.reviewId+'/resolve','POST',{resolution:'DISMISSED'},'Dismiss this integration review item?',ev.currentTarget)}));return d}
async function loadView(){if(!token)return;try{e.controls.replaceChildren();if(view==='staff'){var d=await api('/api/v1/admin/staff?limit=100');controls('Grant a school role',[{name:'userId',label:'Staff user ID',required:true},{name:'role',label:'Role',type:'select',options:[{value:'TEACHER',label:'Teacher'},{value:'SECURITY',label:'Security'},{value:'ADMIN',label:'Administrator'}]}],function(f){mutate('/api/v1/admin/staff/'+f.elements.userId.value.trim()+'/roles','POST',{role:f.elements.role.value},'Grant '+f.elements.role.value+' to this staff member?',f.querySelector('button[type=submit]'))});table(['Staff','Email','Status','Current roles'],d.rows.map(function(r){return[r.displayName,r.primaryEmail,r.status,r.roles.map(function(x){return x.role}).join(', ')||'None']}))}
else if(view==='sections'){var s=await api('/api/v1/admin/sections?limit=100');table(['Section','Period','Room','Source','Staff','Students','Status','Action'],s.rows.map(function(r){return[r.name,r.periodCode||'—',r.room||'—',r.source,r.staffCount,r.activeEnrollmentCount,r.status,sectionActions(r)]}))}
else if(view==='enrollments'){var en=await api('/api/v1/admin/enrollments?limit=100');table(['Student','Section','Source','Status','Joined','Left','Action'],en.rows.map(function(r){return[r.studentName,r.sectionName,r.source,r.status,new Date(r.joinedAt).toLocaleDateString(),r.leftAt?new Date(r.leftAt).toLocaleString():'—',enrollmentActions(r)]}))}
else if(view==='schedules'){var sc=await api('/api/v1/admin/schedules');controls('Create schedule profile',[{name:'name',label:'Profile name',required:true},{name:'key',label:'Profile key',required:true,placeholder:'ASSEMBLY_DAY'}],function(f){mutate('/api/v1/admin/schedules','POST',{name:f.elements.name.value.trim(),key:f.elements.key.value.trim()},'Create this schedule profile?',f.querySelector('button[type=submit]'))});table(['Schedule','Key','Status','Periods'],sc.rows.map(function(r){return[r.name,r.key,r.status,r.periods.map(function(p){return p.periodCode+' '+p.startsAtLocal.slice(0,5)+'–'+p.endsAtLocal.slice(0,5)}).join('; ')||'No periods']}))}
else if(view==='calendar'){var today=new Date(),from=dateOnly(new Date(today.getTime()-14*86400000)),to=dateOnly(new Date(today.getTime()+45*86400000));var cal=await api('/api/v1/admin/calendar?from='+from+'&to='+to);controls('Set a calendar day',[{name:'academicDate',label:'Date',type:'date',required:true,value:dateOnly(today)},{name:'isSchoolDay',label:'Day type',type:'select',options:[{value:'true',label:'School day'},{value:'false',label:'No school'}]},{name:'scheduleProfileId',label:'Schedule profile ID',placeholder:'Optional if schedule is not yet assigned'},{name:'label',label:'Label'}],function(f){var school=f.elements.isSchoolDay.value==='true',profile=f.elements.scheduleProfileId.value.trim();mutate('/api/v1/admin/calendar/day','PUT',{academicDate:f.elements.academicDate.value,isSchoolDay:school,scheduleProfileId:profile||null,label:f.elements.label.value.trim()||null},'Save this school calendar day?',f.querySelector('button[type=submit]'))});table(['Date','School day','Schedule','Label','Source'],cal.rows.map(function(r){return[r.academicDate,r.isSchoolDay?'Yes':'No',r.scheduleProfileName||'—',r.label||'—',r.source]}))}
else if(view==='policies'){var p=await api('/api/v1/admin/policies?limit=200');controls('Update a policy value',[{name:'policyValueId',label:'Policy value ID',required:true},{name:'typedValue',label:'JSON value',required:true,placeholder:'Example: 3'},{name:'teacherOverrideAllowed',label:'Teacher configurable',type:'select',options:[{value:'false',label:'No'},{value:'true',label:'Yes'}]}],function(f){var parsed;try{parsed=JSON.parse(f.elements.typedValue.value)}catch(_err){e.status.textContent='Policy value must be valid JSON.';return}mutate('/api/v1/admin/policies/'+f.elements.policyValueId.value.trim(),'PUT',{typedValue:parsed,teacherOverrideAllowed:f.elements.teacherOverrideAllowed.value==='true'},'Update this school policy value?',f.querySelector('button[type=submit]'))});table(['Policy','Set','Value','Teacher configurable','Effective','ID'],p.rows.map(function(r){return[r.policyKey,r.policySetName,JSON.stringify(r.typedValue),r.teacherOverrideAllowed?'Yes':'No',r.effectiveFrom+(r.effectiveUntil?' → '+r.effectiveUntil:''),r.policyValueId]}))}
else if(view==='destinations'){var x=await api('/api/v1/admin/destinations');table(['Destination','Category','Student','Security','Capacity','Status','Action'],x.rows.map(function(r){return[r.name,r.category,r.studentSelectable?'Yes':'No',r.securityVisible?'Yes':'No',r.capacity||'—',r.active?'ACTIVE':'INACTIVE',destinationActions(r)]}))}
else if(view==='access'){var ac=await api('/api/v1/admin/student-access?limit=100');controls('Create student access exception',[{name:'studentId',label:'Student ID',required:true},{name:'sectionId',label:'Section ID',placeholder:'Optional — leave blank for schoolwide rule'},{name:'accessMode',label:'Access mode',type:'select',options:[{value:'STANDARD',label:'Standard'},{value:'UNLIMITED',label:'Unlimited'},{value:'ESCORT_ONLY',label:'Escort only'}]},{name:'validUntil',label:'Valid until',type:'datetime-local'},{name:'reasonPrivate',label:'Private exception reason',type:'textarea',required:true,span2:true}],function(f){mutate('/api/v1/admin/student-access','POST',{studentId:f.elements.studentId.value.trim(),sectionId:f.elements.sectionId.value.trim()||null,accessMode:f.elements.accessMode.value,reasonPrivate:f.elements.reasonPrivate.value.trim(),validFrom:new Date().toISOString(),validUntil:f.elements.validUntil.value?new Date(f.elements.validUntil.value).toISOString():null},'Create this student access exception?',f.querySelector('button[type=submit]'))});table(['Student','Section','Mode','Private reason','Valid from','Valid until','Status'],ac.rows.map(function(r){return[r.studentName,r.sectionName||'Schoolwide',r.accessMode,r.reasonPrivate||'—',new Date(r.validFrom).toLocaleString(),r.validUntil?new Date(r.validUntil).toLocaleString():'Open',r.status]}))}
else if(view==='reviews'){var q=await api('/api/v1/admin/integrations/reviews?limit=100');table(['Type','External key','Reason','Status','Created','Action'],q.rows.map(function(r){return[r.reviewType,r.externalKey,r.reason,r.status,new Date(r.createdAt).toLocaleString(),reviewActions(r)]}))}
else{var a=await api('/api/v1/admin/audit?limit=50');table(['Time','Actor','Action','Target','Source','Reason'],a.rows.map(function(r){return[new Date(r.occurredAt).toLocaleString(),r.actorDisplayName||r.actorKind,r.action,r.targetType+(r.targetId?' · '+r.targetId:''),r.source,r.reason||'—']}))}e.status.textContent='Bounded '+view+' view refreshed.'}catch(err){e.status.textContent=err.message}}
async function refresh(){if(!token){setConnection();return}try{renderOverview(await api('/api/v1/admin/overview'));await loadView();setConnection()}catch(err){e.status.textContent=err.message}}
document.querySelectorAll('[role="tab"]').forEach(function(b){b.addEventListener('click',function(){document.querySelectorAll('[role="tab"]').forEach(function(x){x.setAttribute('aria-selected','false')});b.setAttribute('aria-selected','true');view=b.dataset.view;loadView()})});e.dialog.addEventListener('close',function(){if(returnFocus&&document.contains(returnFocus))returnFocus.focus();returnFocus=null;pending=null});e.confirm.addEventListener('click',function(ev){if(pending){ev.preventDefault();var reason=e.reason.value.trim();if(!reason){e.dialogStatus.textContent='A private administrative reason is required.';e.reason.focus();return}pending(reason)}});
window.grantDeskAdminSession=function(value){token=String(value||'').trim();if(token)sessionStorage.setItem(key,token);else sessionStorage.removeItem(key);setConnection();refresh()};window.grantDeskAdminConfirm=function(buttonNode,description,fn){returnFocus=buttonNode&&buttonNode.focus?buttonNode:document.activeElement;pending=fn;e.description.textContent=description;e.reason.value='';e.dialogStatus.textContent='';e.dialog.showModal();setTimeout(function(){e.reason.focus()},0)};setConnection();if(token)refresh();})();</script></body></html>`;
}
