export function adminConsoleHtml(): string {
  return String.raw`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>GrantDesk Admin</title>
<style>
:root{font-family:Inter,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color-scheme:light;background:#f4f6f8;color:#17202a}*{box-sizing:border-box}body{margin:0;background:#f4f6f8}button,input,select,textarea{font:inherit}button,input,select{min-height:44px}button:focus-visible,input:focus-visible,select:focus-visible,textarea:focus-visible{outline:3px solid currentColor;outline-offset:2px}.top{position:sticky;top:0;z-index:5;background:#17202a;color:#fff;padding:14px 20px;display:flex;justify-content:space-between;gap:16px}.wrap{max-width:1500px;margin:auto;padding:20px}.notice,.card,.panel{background:#fff;border:1px solid #d6dde3;border-radius:12px}.notice{padding:12px 14px;margin-bottom:16px}.metrics{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:12px;margin-bottom:16px}.card{padding:16px}.card strong{display:block;font-size:1.7rem}.panel{padding:16px;margin-bottom:16px}h1,h2{margin-top:0}.tabs{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:12px}.btn{border:1px solid #59636d;background:#fff;border-radius:8px;padding:8px 12px;cursor:pointer}.btn.primary{background:#17202a;color:#fff}.btn[aria-selected="true"]{font-weight:800;text-decoration:underline}.table-wrap{overflow:auto}.grid{width:100%;border-collapse:collapse;min-width:760px}.grid th,.grid td{text-align:left;padding:10px;border-bottom:1px solid #e1e6ea;vertical-align:top}.grid th{font-size:.82rem;text-transform:uppercase}.muted{color:#5e6872}.empty{padding:24px;text-align:center;color:#5e6872}.status{min-height:1.4em;margin:8px 0}.health{display:flex;gap:12px;flex-wrap:wrap}.health span{padding:6px 9px;border:1px solid #d6dde3;border-radius:999px}dialog{border:0;border-radius:12px;max-width:560px;width:calc(100% - 32px);box-shadow:0 20px 60px rgba(0,0,0,.25)}dialog::backdrop{background:rgba(0,0,0,.45)}dialog form{display:grid;gap:12px}.field{display:grid;gap:5px}.field label{font-weight:700}.field input,.field select,.field textarea{border:1px solid #9da9b3;border-radius:8px;padding:9px 10px;background:#fff}.field textarea{min-height:110px;resize:vertical}.actions{display:flex;gap:8px;justify-content:flex-end;flex-wrap:wrap}@media(max-width:950px){.metrics{grid-template-columns:repeat(2,1fr)}}@media(max-width:520px){.wrap{padding:12px}.metrics{grid-template-columns:1fr}.top{flex-direction:column}}
</style></head><body>
<header class="top"><strong>GrantDesk · Admin</strong><span id="connection">Staff session required</span></header>
<main class="wrap">
<div class="notice">School-scoped administration only. Secret credentials and external authorization material are never shown here. Unrestricted lifetime exports, Security force-close, and Classroom write-back are not available.</div>
<section class="metrics" aria-label="School administration summary"><div class="card">Active staff<strong id="staffCount">—</strong></div><div class="card">Active sections<strong id="sectionCount">—</strong></div><div class="card">Active students<strong id="studentCount">—</strong></div><div class="card">Open reviews<strong id="reviewCount">—</strong></div><div class="card">Destinations<strong id="destinationCount">—</strong></div></section>
<section class="panel"><h1>School administration</h1><div class="health" id="health" aria-label="Classroom integration health"></div><div id="status" class="status" role="status" aria-live="polite"></div><div class="tabs" role="tablist" aria-label="Administration views"><button class="btn" role="tab" aria-selected="true" data-view="staff">Staff & roles</button><button class="btn" role="tab" aria-selected="false" data-view="sections">Sections</button><button class="btn" role="tab" aria-selected="false" data-view="policies">Policies</button><button class="btn" role="tab" aria-selected="false" data-view="destinations">Destinations</button><button class="btn" role="tab" aria-selected="false" data-view="reviews">Integration reviews</button><button class="btn" role="tab" aria-selected="false" data-view="audit">Audit</button></div><div class="table-wrap" id="content"><div class="empty">Connect an administrator staff session to load school configuration.</div></div></section>
</main>
<dialog id="reasonDialog" aria-labelledby="dialogTitle"><form method="dialog" id="reasonForm"><h2 id="dialogTitle">Confirm administrator action</h2><p id="dialogDescription"></p><div class="field"><label for="reason">Private administrative reason</label><textarea id="reason" maxlength="1000" required></textarea></div><div class="actions"><button class="btn" value="cancel">Cancel</button><button class="btn primary" id="confirm" value="default">Confirm</button></div><div id="dialogStatus" role="status" aria-live="polite"></div></form></dialog>
<script>(function(){'use strict';
var key='grantdesk.schoolwide.staffToken',token=sessionStorage.getItem(key)||'',view='staff',returnFocus=null,pending=null;
var e={connection:document.getElementById('connection'),status:document.getElementById('status'),content:document.getElementById('content'),staff:document.getElementById('staffCount'),sections:document.getElementById('sectionCount'),students:document.getElementById('studentCount'),reviews:document.getElementById('reviewCount'),destinations:document.getElementById('destinationCount'),health:document.getElementById('health'),dialog:document.getElementById('reasonDialog'),description:document.getElementById('dialogDescription'),reason:document.getElementById('reason'),dialogStatus:document.getElementById('dialogStatus'),confirm:document.getElementById('confirm')};
function headers(extra){var h={authorization:'Bearer '+token};if(extra)Object.keys(extra).forEach(function(k){h[k]=extra[k]});return h}function text(tag,value,cls){var n=document.createElement(tag);n.textContent=value;if(cls)n.className=cls;return n}function rid(){return crypto.randomUUID()}async function api(url,options){options=options||{};options.headers=headers(options.headers||{});var r=await fetch(url,options),b={};try{b=await r.json()}catch(_e){}if(r.status===401){token='';sessionStorage.removeItem(key);setConnection()}if(!r.ok)throw new Error(b.message||('Request failed ('+r.status+')'));return b}function setConnection(){e.connection.textContent=token?'Administrator session connected':'Staff session required'}
function renderOverview(o){e.staff.textContent=o.summary.activeStaff;e.sections.textContent=o.summary.activeSections;e.students.textContent=o.summary.activeStudents;e.reviews.textContent=o.summary.openIntegrationReviews;e.destinations.textContent=o.summary.activeDestinations;e.health.replaceChildren();[['Classroom active',o.integrationHealth.active],['Revoked',o.integrationHealth.revoked],['Error',o.integrationHealth.error],['Stale links',o.integrationHealth.staleLinks]].forEach(function(x){e.health.appendChild(text('span',x[0]+': '+x[1]))})}
function table(headers,rows){e.content.replaceChildren();if(!rows.length){e.content.appendChild(text('div','No records in this bounded view.','empty'));return}var t=document.createElement('table');t.className='grid';var th=document.createElement('thead'),tr=document.createElement('tr');headers.forEach(function(h){tr.appendChild(text('th',h))});th.appendChild(tr);t.appendChild(th);var tb=document.createElement('tbody');rows.forEach(function(cells){var r=document.createElement('tr');cells.forEach(function(c){var td=document.createElement('td');if(c instanceof Node)td.appendChild(c);else td.textContent=String(c);r.appendChild(td)});tb.appendChild(r)});t.appendChild(tb);e.content.appendChild(t)}
async function loadView(){if(!token)return;try{if(view==='staff'){var d=await api('/api/v1/admin/staff?limit=100');table(['Staff','Email','Status','Current roles'],d.rows.map(function(r){return[r.displayName,r.primaryEmail,r.status,r.roles.map(function(x){return x.role}).join(', ')||'None']}))}else if(view==='sections'){var s=await api('/api/v1/admin/sections?limit=100');table(['Section','Period','Room','Source','Staff','Students','Status'],s.rows.map(function(r){return[r.name,r.periodCode||'—',r.room||'—',r.source,r.staffCount,r.activeEnrollmentCount,r.status]}))}else if(view==='policies'){var p=await api('/api/v1/admin/policies?limit=200');table(['Policy','Set','Value','Teacher configurable','Effective'],p.rows.map(function(r){return[r.policyKey,r.policySetName,JSON.stringify(r.typedValue),r.teacherOverrideAllowed?'Yes':'No',r.effectiveFrom+(r.effectiveUntil?' → '+r.effectiveUntil:'')]}))}else if(view==='destinations'){var x=await api('/api/v1/admin/destinations');table(['Destination','Category','Student','Security','Capacity','Status'],x.rows.map(function(r){return[r.name,r.category,r.studentSelectable?'Yes':'No',r.securityVisible?'Yes':'No',r.capacity||'—',r.active?'ACTIVE':'INACTIVE']}))}else if(view==='reviews'){var q=await api('/api/v1/admin/integrations/reviews?limit=100');table(['Type','External key','Reason','Status','Created'],q.rows.map(function(r){return[r.reviewType,r.externalKey,r.reason,r.status,new Date(r.createdAt).toLocaleString()]}))}else{var a=await api('/api/v1/admin/audit?limit=50');table(['Time','Actor','Action','Target','Source','Reason'],a.rows.map(function(r){return[new Date(r.occurredAt).toLocaleString(),r.actorDisplayName||r.actorKind,r.action,r.targetType+(r.targetId?' · '+r.targetId:''),r.source,r.reason||'—']}))}e.status.textContent='Bounded '+view+' view refreshed.'}catch(err){e.status.textContent=err.message}}
async function refresh(){if(!token){setConnection();return}try{renderOverview(await api('/api/v1/admin/overview'));await loadView();setConnection()}catch(err){e.status.textContent=err.message}}
document.querySelectorAll('[role="tab"]').forEach(function(b){b.addEventListener('click',function(){document.querySelectorAll('[role="tab"]').forEach(function(x){x.setAttribute('aria-selected','false')});b.setAttribute('aria-selected','true');view=b.dataset.view;loadView()})});e.dialog.addEventListener('close',function(){if(returnFocus&&document.contains(returnFocus))returnFocus.focus();returnFocus=null;pending=null});e.confirm.addEventListener('click',function(ev){if(pending){ev.preventDefault();var reason=e.reason.value.trim();if(!reason){e.dialogStatus.textContent='A private administrative reason is required.';e.reason.focus();return}pending(reason)}});
window.grantDeskAdminSession=function(value){token=String(value||'').trim();if(token)sessionStorage.setItem(key,token);else sessionStorage.removeItem(key);setConnection();refresh()};window.grantDeskAdminConfirm=function(button,description,fn){returnFocus=button;pending=fn;e.description.textContent=description;e.reason.value='';e.dialogStatus.textContent='';e.dialog.showModal();setTimeout(function(){e.reason.focus()},0)};setConnection();if(token)refresh();})();</script></body></html>`;
}
