import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import test from 'node:test';
import { Pool, type PoolClient, type QueryResultRow } from 'pg';
import { buildApp } from '../app.js';
import { AuthenticationError, type StaffIdentityProvider, type VerifiedStaffIdentity } from '../auth/types.js';
import type { AppConfig } from '../config.js';
import type { QueryExecutor, TransactionalDatabase } from '../db/database.js';
import { seedHallPassFixture } from '../hall-pass/test-fixtures.js';

const databaseUrl=process.env.DATABASE_URL;
const adminId='00000000-0000-0000-0000-000000000563';
const config:AppConfig={nodeEnv:'test',host:'127.0.0.1',port:8787,logLevel:'silent',databaseUrl:'postgresql://fixture.invalid/schoolwide',dbPoolMax:2,instanceId:'sw160-test',legacyReadAdapterMode:'disabled',legacyProductionWrites:'forbidden'};
class SavepointDatabase implements TransactionalDatabase{readonly #client:PoolClient;#counter=0;constructor(client:PoolClient){this.#client=client;}async query<T extends QueryResultRow=QueryResultRow>(sql:string,parameters:readonly unknown[]=[]):Promise<readonly T[]>{return(await this.#client.query<T>(sql,[...parameters])).rows;}async transaction<T>(work:(transaction:QueryExecutor)=>Promise<T>):Promise<T>{const sp=`sw160_${++this.#counter}`;await this.#client.query(`SAVEPOINT ${sp}`);try{const result=await work(this);await this.#client.query(`RELEASE SAVEPOINT ${sp}`);return result;}catch(error){await this.#client.query(`ROLLBACK TO SAVEPOINT ${sp}`);await this.#client.query(`RELEASE SAVEPOINT ${sp}`);throw error;}}async close():Promise<void>{}}
class FixtureIdentityProvider implements StaffIdentityProvider{async verify(assertion:string):Promise<VerifiedStaffIdentity>{if(assertion==='admin')return{provider:'SYNTHETIC',subject:'google-sw160-admin'};if(assertion==='teacher')return{provider:'SYNTHETIC',subject:'google-teacher-alpha'};throw new AuthenticationError('Synthetic identity assertion rejected.');}}
const hash=(value:string)=>createHash('sha256').update(value.trim().toLowerCase(),'utf8').digest('hex');
async function signIn(app:ReturnType<typeof buildApp>,assertion:string):Promise<string>{const response=await app.inject({method:'POST',url:'/auth/session',payload:{assertion}});assert.equal(response.statusCode,201,response.body);return response.json<{token:string}>().token;}
const auth=(token:string)=>({authorization:`Bearer ${token}`,'content-type':'application/json'});
let shadowSeedSequence=0;
async function seedCertifiedShadow(client:PoolClient,ids:{orgA:string;schoolA:string;studentA:string;studentA2:string},options:{credentialForA:boolean;includeAliasA2:boolean}):Promise<string>{
  shadowSeedSequence+=1;const suffix=String(shadowSeedSequence);const keyA=`legacy-a-${suffix}`,keyA2=`legacy-a2-${suffix}`;
  await client.query(`INSERT INTO student_identity_aliases (school_id,student_id,kind,value,normalized_value,source) VALUES ($1,$2,'LEGACY_STUDENT_KEY',$3,$3,'LEGACY_IMPORT')`,[ids.schoolA,ids.studentA,keyA]);
  if(options.includeAliasA2)await client.query(`INSERT INTO student_identity_aliases (school_id,student_id,kind,value,normalized_value,source) VALUES ($1,$2,'LEGACY_STUDENT_KEY',$3,$3,'LEGACY_IMPORT')`,[ids.schoolA,ids.studentA2,keyA2]);
  if(options.credentialForA)await client.query(`INSERT INTO student_credentials (school_id,student_id,verifier_scheme,secret_hash,secret_salt,verifier_params) VALUES ($1,$2,'SCRYPT_PEPPER_V1',$3,$4,'{}'::jsonb) ON CONFLICT DO NOTHING`,[ids.schoolA,ids.studentA,'a'.repeat(64),'b'.repeat(32)]);
  const fingerprint=hash(`sw160-shadow-${suffix}`);const run=await client.query<{id:string}>(`INSERT INTO migration_import_runs (organization_id,school_id,source_snapshot_fingerprint,source_alias,source_schema_version,source_exported_at,mode,status,finished_at) VALUES ($1,$2,$3,$4,'2026-09-05-session-a',now(),'IMPORT_SHADOW','PASS',now()) RETURNING id`,[ids.orgA,ids.schoolA,fingerprint,`approved-shadow-v24-${suffix}`]);const runId=run.rows[0]!.id;
  const rows=[{key:keyA,hasCredential:true},{key:keyA2,hasCredential:true}];for(let i=0;i<rows.length;i+=1){const row=rows[i]!;await client.query(`INSERT INTO migration_shadow_records (organization_id,school_id,import_run_id,source_surface,source_ordinal,record_type,identity_key_hash,source_row_hash,state_json) VALUES ($1,$2,$3,'credentialCoverage',$4,'CREDENTIAL_COVERAGE',$5,$6,$7::jsonb)`,[ids.orgA,ids.schoolA,runId,i,hash(row.key),hash(`row-${suffix}-${i}`),JSON.stringify({hasCredential:row.hasCredential})]);}
  await client.query(`INSERT INTO migration_shadow_parity_reports (organization_id,school_id,import_run_id,source_snapshot_fingerprint,overall_status,source_counts_json,shadow_counts_json) VALUES ($1,$2,$3,$4,'PASS','{"credentialCoverage":2}'::jsonb,'{"credentialCoverage":2}'::jsonb)`,[ids.orgA,ids.schoolA,runId,fingerprint]);return runId;
}

if(!databaseUrl){test('SW-160 credential continuity tests require DATABASE_URL',{skip:true},()=>{});}else test('SW-160 Credential Continuity + Recovery Bridge',async(t)=>{const pool=new Pool({connectionString:databaseUrl,max:1});const client=await pool.connect();await client.query('BEGIN');try{const fixture=await seedHallPassFixture(client);await client.query(`INSERT INTO users (id,organization_id,primary_email,display_name,google_subject_id) VALUES ($1,$2,'sw160-admin@north.example.invalid','SW160 Admin','google-sw160-admin')`,[adminId,fixture.orgA]);await client.query(`INSERT INTO staff_profiles (user_id,organization_id,title) VALUES ($1,$2,'Administrator')`,[adminId,fixture.orgA]);await client.query(`INSERT INTO user_roles (organization_id,school_id,user_id,role) VALUES ($1,$2,$3,'ADMIN')`,[fixture.orgA,fixture.schoolA,adminId]);const db=new SavepointDatabase(client),app=buildApp({config,database:db,identityProvider:new FixtureIdentityProvider()});await app.ready();const admin=await signIn(app,'admin'),teacher=await signIn(app,'teacher');
  await t.test('Admin-only continuity plan requires certified PASS shadow evidence',async()=>{const uncertified='11111111-1111-4111-8111-111111111999';const denied=await app.inject({method:'POST',url:'/api/v1/internal/migration/credentials/continuity-plan',headers:auth(teacher),payload:{shadowImportRunId:uncertified}});assert.equal(denied.statusCode,403,denied.body);const rejected=await app.inject({method:'POST',url:'/api/v1/internal/migration/credentials/continuity-plan',headers:auth(admin),payload:{shadowImportRunId:uncertified}});assert.equal(rejected.statusCode,409,rejected.body);assert.match(rejected.body,/SHADOW_NOT_CERTIFIED/);});
  await t.test('continuity plan preserves strong credential, requires reprovision for missing credential, and writes no secrets',async()=>{const runId=await seedCertifiedShadow(client,fixture,{credentialForA:true,includeAliasA2:true});const before=await client.query<{count:string}>(`SELECT count(*)::text AS count FROM student_credentials WHERE school_id=$1`,[fixture.schoolA]);const response=await app.inject({method:'POST',url:'/api/v1/internal/migration/credentials/continuity-plan',headers:auth(admin),payload:{shadowImportRunId:runId}});assert.equal(response.statusCode,200,response.body);const body=response.json<{status:string;counts:{preserve:number;provisionRequired:number;blocked:number};legacyWrites:number;credentialSecretWrites:number;recoveryArtifact:unknown}>();assert.equal(body.status,'PASS');assert.deepEqual(body.counts,{preserve:1,provisionRequired:1,blocked:0});assert.equal(body.legacyWrites,0);assert.equal(body.credentialSecretWrites,0);const after=await client.query<{count:string}>(`SELECT count(*)::text AS count FROM student_credentials WHERE school_id=$1`,[fixture.schoolA]);assert.equal(after.rows[0]?.count,before.rows[0]?.count);const serialized=JSON.stringify(body);assert.doesNotMatch(serialized,/secret_hash|secret_salt|PIN_SALT|"pin"\s*:|"actionProof"\s*:|"proofSecret"\s*:|123456/i);});
  await t.test('unmatched legacy identity blocks PASS rather than guessing',async()=>{const runId=await seedCertifiedShadow(client,fixture,{credentialForA:false,includeAliasA2:false});const response=await app.inject({method:'POST',url:'/api/v1/internal/migration/credentials/continuity-plan',headers:auth(admin),payload:{shadowImportRunId:runId}});assert.equal(response.statusCode,200,response.body);const body=response.json<{status:string;counts:{blocked:number};records:{studentId:string|null;continuityAction:string}[]}>();assert.equal(body.status,'REVIEW');assert.equal(body.counts.blocked,1);assert.ok(body.records.some((record)=>record.studentId===null&&record.continuityAction==='BLOCKED'));});
  await t.test('same certified shadow run replays one deterministic recovery artifact',async()=>{const runId=await seedCertifiedShadow(client,fixture,{credentialForA:false,includeAliasA2:true});const first=await app.inject({method:'POST',url:'/api/v1/internal/migration/credentials/continuity-plan',headers:auth(admin),payload:{shadowImportRunId:runId}});const second=await app.inject({method:'POST',url:'/api/v1/internal/migration/credentials/continuity-plan',headers:auth(admin),payload:{shadowImportRunId:runId}});const a=first.json<{continuityRunId:string;artifactDigest:string}>(),b=second.json<{continuityRunId:string;artifactDigest:string;replayed:boolean}>();assert.equal(b.replayed,true);assert.equal(b.continuityRunId,a.continuityRunId);assert.equal(b.artifactDigest,a.artifactDigest);});
  await app.close();}finally{await client.query('ROLLBACK');client.release();await pool.end();}});
